import { createHash } from 'node:crypto';

import type { ConversationBuyingSignal, ContactabilityAssessment, ConversationEvidenceRef, CustomerJourneyContext } from './customer-engagement.js';

export type CustomerLifecycleState = 'UNKNOWN' | 'ANONYMOUS' | 'PROSPECT' | 'LEAD' | 'ENGAGED_LEAD' | 'QUALIFIED_LEAD' | 'OPPORTUNITY' | 'CUSTOMER' | 'ACTIVE_CUSTOMER' | 'AT_RISK' | 'DORMANT' | 'CHURNED' | 'RENEWAL_DUE' | 'EXPANSION_CANDIDATE' | 'ADVOCATE';
export type JourneyEventType = 'CAMPAIGN_EXPOSURE' | 'AD_CLICK' | 'SITE_VISIT' | 'FORM_SUBMISSION' | 'LEAD_CREATED' | 'IDENTITY_RESOLVED' | 'CONVERSATION_STARTED' | 'CUSTOMER_REPLIED' | 'HIGH_INTENT_SIGNAL' | 'QUALIFIED' | 'MEETING_REQUESTED' | 'HANDOFF' | 'OPPORTUNITY_CREATED' | 'OPPORTUNITY_ADVANCED' | 'PROPOSAL' | 'CLOSED_WON' | 'REVENUE_VERIFIED' | 'RENEWAL_SIGNAL' | 'EXPANSION_SIGNAL' | 'COMPLAINT' | 'SUPPORT_ESCALATION' | 'OPT_OUT' | 'DORMANCY_SIGNAL' | 'CHURN_SIGNAL' | 'OTHER';
export type JourneyAction = 'NO_ACTION' | 'ASK_CLARIFYING_QUESTION' | 'SHARE_INFORMATION' | 'QUALIFY' | 'FOLLOW_UP' | 'OFFER_MEETING' | 'HANDOFF_SALES' | 'HANDOFF_SUPPORT' | 'CREATE_OPPORTUNITY_RECOMMENDATION' | 'ADVANCE_OPPORTUNITY_RECOMMENDATION' | 'NURTURE' | 'REENGAGE' | 'RETENTION_OUTREACH' | 'RENEWAL_OUTREACH' | 'EXPANSION_OUTREACH' | 'REQUEST_FEEDBACK' | 'REQUEST_REVIEW' | 'ESCALATE' | 'DO_NOT_CONTACT';
export type JourneyCapability = 'CONVERSATIONS' | 'EMAIL' | 'SMS' | 'WHATSAPP' | 'WEB_CHAT' | 'VOICE' | 'CRM' | 'CALENDAR' | 'AI_RECEPTIONIST' | 'REPUTATION_REVIEWS' | 'LOCAL_PRESENCE' | 'LEAD_MANAGEMENT';
export type EligibilityResult = 'ELIGIBLE' | 'INELIGIBLE' | 'REQUIRES_APPROVAL' | 'INSUFFICIENT_EVIDENCE' | 'BLOCKED' | 'UNKNOWN';
export type PlanStepStatus = 'PLANNED' | 'ELIGIBLE' | 'BLOCKED' | 'WAITING' | 'RECOMMENDED' | 'COMPLETED' | 'SKIPPED' | 'EXPIRED' | 'CANCELLED';
export type JourneyOutcomeType = 'CUSTOMER_RESPONDED' | 'MEETING_REQUESTED' | 'MEETING_COMPLETED' | 'HANDOFF_ACCEPTED' | 'QUALIFIED' | 'OPPORTUNITY_CREATED' | 'OPPORTUNITY_ADVANCED' | 'REVENUE_VERIFIED' | 'RENEWED' | 'EXPANDED' | 'NO_RESPONSE' | 'OPTED_OUT' | 'NEGATIVE_RESPONSE' | 'UNKNOWN';

export interface CustomerJourneyEvent { eventId: string; tenantId: string; identityId?: string; leadId?: string; organizationId?: string; brandId?: string; businessUnitId?: string; locationId?: string; type: JourneyEventType; occurredAt: string; source: string; provider?: string; idempotencyKey: string; campaignRef?: string; conversationRef?: string; opportunityRef?: string; revenueRef?: string; verificationState: 'OBSERVED' | 'VERIFIED' | 'UNVERIFIED' | 'UNKNOWN'; evidenceRefs: ConversationEvidenceRef[]; provenance: string; }
export interface CustomerJourneyTimeline { tenantId: string; identityId: string; events: CustomerJourneyEvent[]; limitations: string[]; }
export interface CustomerLifecycleAssessment { assessmentId: string; tenantId: string; identityId: string; leadId?: string; opportunityId?: string; currentState: CustomerLifecycleState; previousState?: CustomerLifecycleState; reasonCodes: string[]; evidenceRefs: ConversationEvidenceRef[]; confidence: number; effectiveAt: string; freshness: 'FRESH' | 'STALE' | 'UNKNOWN'; limitations: string[]; }
export interface JourneyStageAssessment { assessmentId: string; tenantId: string; identityId: string; currentState: CustomerLifecycleState; previousState?: CustomerLifecycleState; stageEntryAt?: string; timeInStageMs?: number; progressionEvidence: ConversationEvidenceRef[]; regressionEvidence: ConversationEvidenceRef[]; blockers: string[]; unknowns: string[]; staleness: 'FRESH' | 'STALE' | 'UNKNOWN'; confidence: number; assessedAt: string; }
export interface ActionEligibilityAssessment { assessmentId: string; tenantId: string; identityId: string; action: JourneyAction; result: EligibilityResult; reasonCodes: string[]; evidenceRefs: ConversationEvidenceRef[]; requiredConsent: boolean; requiredPolicy: boolean; requiredApproval: boolean; eligibleCapabilities: JourneyCapability[]; limitations: string[]; assessedAt: string; }
export interface NextBestActionRecommendation { recommendationId: string; deterministicKey: string; tenantId: string; identityId: string; lifecycleState: CustomerLifecycleState; action: JourneyAction; reasonCodes: string[]; evidenceRefs: ConversationEvidenceRef[]; confidence: number; priority: 'LOW' | 'NORMAL' | 'HIGH' | 'URGENT'; expectedOutcome: string; eligibleCapabilities: JourneyCapability[]; requiredConsent: boolean; requiredPolicy: boolean; requiredApproval: boolean; eligibility: EligibilityResult; expiresAt: string; rank?: number; tradeoffs: string[]; limitations: string[]; state: 'RECOMMENDATION_ONLY'; createdAt: string; }
export interface CustomerJourneyPlanStep { sequence: number; action: JourneyAction | 'WAIT_FOR_RESPONSE' | 'HUMAN_HANDOFF' | 'IDENTIFY_NEED'; trigger: string; timing: string; eligibleCapabilities: JourneyCapability[]; requiredEvidence: string[]; consentRequired: boolean; policyRequired: boolean; approvalRequired: boolean; expiresAt?: string; status: PlanStepStatus; }
export interface CustomerJourneyPlan { planId: string; tenantId: string; identityId: string; lifecycleState: CustomerLifecycleState; steps: CustomerJourneyPlanStep[]; state: 'RECOMMENDATION_ONLY'; createdAt: string; limitations: string[]; }
export interface JourneyTrigger { triggerId: string; tenantId: string; identityId: string; type: 'NEW_LEAD' | 'CUSTOMER_REPLIED' | 'HIGH_INTENT' | 'MEETING_REQUESTED' | 'QUALIFIED_NO_OPPORTUNITY' | 'OPPORTUNITY_STALLED' | 'NO_RESPONSE' | 'CUSTOMER_DORMANT' | 'RENEWAL_WINDOW' | 'EXPANSION_SIGNAL' | 'COMPLAINT' | 'NEGATIVE_SENTIMENT_SIGNAL' | 'OPT_OUT' | 'REVENUE_VERIFIED' | 'CHURN_RISK_SIGNAL'; deterministicKey: string; evidenceRefs: ConversationEvidenceRef[]; occurredAt: string; }
export interface ContactFrequencyAssessment { tenantId: string; identityId: string; channel?: JourneyCapability; purpose: string; result: 'OK' | 'COOLDOWN' | 'BLOCKED' | 'INSUFFICIENT_DATA'; recentAttempts: number; recentResponses: number; cooldownUntil?: string; reasonCodes: string[]; }
export interface RetentionRiskAssessment { tenantId: string; identityId: string; level: 'LOW' | 'MEDIUM' | 'HIGH' | 'INSUFFICIENT_DATA' | 'UNKNOWN'; reasonCodes: string[]; evidenceRefs: ConversationEvidenceRef[]; limitations: string[]; assessedAt: string; }
export interface RenewalAssessment { tenantId: string; identityId: string; renewalDate?: string; renewalWindow: 'DUE' | 'UPCOMING' | 'UNKNOWN'; customerStatus: CustomerLifecycleState; recommendation: JourneyAction; handoffRecommended: boolean; evidenceRefs: ConversationEvidenceRef[]; limitations: string[]; }
export interface ExpansionOpportunityAssessment { tenantId: string; identityId: string; strength: 'STRONG' | 'POSSIBLE' | 'NONE' | 'INSUFFICIENT_DATA'; reasonCodes: string[]; evidenceRefs: ConversationEvidenceRef[]; recommendation: JourneyAction; limitations: string[]; }
export interface CustomerHealthAssessment { tenantId: string; identityId: string; health: 'HEALTHY' | 'WATCH' | 'AT_RISK' | 'INSUFFICIENT_DATA' | 'UNKNOWN'; dimensions: Record<string, 'POSITIVE' | 'NEUTRAL' | 'CONCERN' | 'UNKNOWN'>; reasonCodes: string[]; evidenceRefs: ConversationEvidenceRef[]; limitations: string[]; }
export interface JourneyBlockerDiagnostic { diagnosticId: string; tenantId: string; identityId: string; type: 'MISSING_IDENTITY' | 'MISSING_CONTACTABILITY' | 'UNRESOLVED_QUESTION' | 'UNRESOLVED_COMMITMENT' | 'NO_HANDOFF' | 'QUALIFIED_NO_OPPORTUNITY' | 'STALE_OPPORTUNITY' | 'MEETING_REQUEST_UNACTIONED' | 'PRICING_REQUEST_UNACTIONED' | 'PROPOSAL_STALLED' | 'RENEWAL_UNACTIONED' | 'CUSTOMER_AT_RISK' | 'OPTED_OUT' | 'PROVIDER_CAPABILITY_UNAVAILABLE' | 'INSUFFICIENT_EVIDENCE'; severity: 'INFO' | 'WARNING' | 'HIGH'; reasonCodes: string[]; evidenceRefs: ConversationEvidenceRef[]; recommendedNextStep: JourneyAction; limitations: string[]; generatedAt: string; }
export interface JourneyActionOutcome { outcomeId: string; tenantId: string; identityId: string; recommendationId?: string; type: JourneyOutcomeType; observedAt: string; verificationState: 'OBSERVED' | 'VERIFIED' | 'UNKNOWN'; idempotencyKey: string; evidenceRefs: ConversationEvidenceRef[]; associationRule?: string; limitations: string[]; }
export interface JourneyLearningRecord { learningId: string; tenantId: string; identityId: string; recommendationType: JourneyAction; journeyState: CustomerLifecycleState; outcome: JourneyOutcomeType; capability?: JourneyCapability; evidenceRefs: ConversationEvidenceRef[]; recordedAt: string; limitations: string[]; }

const hash = (prefix: string, value: unknown) => `${prefix}-${createHash('sha256').update(JSON.stringify(value)).digest('hex').slice(0, 24)}`;
const clone = <T>(value: T): T => structuredClone(value);
const isOutbound = (action: JourneyAction) => !['NO_ACTION', 'DO_NOT_CONTACT', 'ESCALATE', 'HANDOFF_SALES', 'HANDOFF_SUPPORT', 'CREATE_OPPORTUNITY_RECOMMENDATION', 'ADVANCE_OPPORTUNITY_RECOMMENDATION'].includes(action);
const has = (events: CustomerJourneyEvent[], type: JourneyEventType) => events.filter((event) => event.type === type);
const evidence = (events: CustomerJourneyEvent[]) => events.flatMap((event) => event.evidenceRefs);

/** Only evidence-backed lifecycle moves are valid; UNKNOWN is not a negative state. */
export function assessLifecycle(input: { tenantId: string; identityId: string; leadId?: string; opportunityId?: string; previous?: CustomerLifecycleAssessment; events: CustomerJourneyEvent[]; now?: string }): CustomerLifecycleAssessment {
  const events = orderJourneyEvents(input.events); const verified = has(events, 'REVENUE_VERIFIED').length > 0 || has(events, 'CLOSED_WON').length > 0;
  let state: CustomerLifecycleState = 'UNKNOWN'; let reasons: string[] = ['NO_AUTHORITATIVE_LIFECYCLE_EVIDENCE'];
  if (has(events, 'CHURN_SIGNAL').length) { state = 'CHURNED'; reasons = ['CHURN_SIGNAL']; }
  else if (has(events, 'OPT_OUT').length) { state = input.previous?.currentState ?? 'UNKNOWN'; reasons = ['OPT_OUT_DOES_NOT_INFER_LIFECYCLE']; }
  else if (has(events, 'COMPLAINT').length || has(events, 'SUPPORT_ESCALATION').length) { state = verified ? 'AT_RISK' : (input.previous?.currentState ?? 'UNKNOWN'); reasons = ['CUSTOMER_RISK_SIGNAL']; }
  else if (has(events, 'DORMANCY_SIGNAL').length) { state = 'DORMANT'; reasons = ['EVIDENCE_BACKED_DORMANCY_SIGNAL']; }
  else if (has(events, 'RENEWAL_SIGNAL').length) { state = 'RENEWAL_DUE'; reasons = ['RENEWAL_SIGNAL']; }
  else if (has(events, 'EXPANSION_SIGNAL').length) { state = 'EXPANSION_CANDIDATE'; reasons = ['EXPANSION_SIGNAL']; }
  else if (verified) { state = 'ACTIVE_CUSTOMER'; reasons = ['VERIFIED_REVENUE_OR_CLOSED_WON']; }
  else if (has(events, 'OPPORTUNITY_CREATED').length || input.opportunityId) { state = 'OPPORTUNITY'; reasons = ['OPPORTUNITY_EVIDENCE']; }
  else if (has(events, 'QUALIFIED').length) { state = 'QUALIFIED_LEAD'; reasons = ['QUALIFICATION_EVIDENCE']; }
  else if (has(events, 'HIGH_INTENT_SIGNAL').length || has(events, 'CUSTOMER_REPLIED').length) { state = 'ENGAGED_LEAD'; reasons = ['ENGAGEMENT_EVIDENCE']; }
  else if (has(events, 'LEAD_CREATED').length || input.leadId) { state = 'LEAD'; reasons = ['LEAD_EVIDENCE']; }
  else if (has(events, 'IDENTITY_RESOLVED').length) { state = 'PROSPECT'; reasons = ['IDENTITY_EVIDENCE']; }
  else if (has(events, 'SITE_VISIT').length || has(events, 'AD_CLICK').length || has(events, 'CAMPAIGN_EXPOSURE').length) { state = 'ANONYMOUS'; reasons = ['ACQUISITION_EVIDENCE']; }
  if (input.previous && input.previous.currentState !== state && !validLifecycleTransition(input.previous.currentState, state)) throw new Error('INVALID_LIFECYCLE_TRANSITION');
  const at = events.at(-1)?.occurredAt ?? input.now ?? new Date().toISOString();
  return { assessmentId: hash('lifecycle', [input.tenantId, input.identityId, state, at]), tenantId: input.tenantId, identityId: input.identityId, ...(input.leadId ? { leadId: input.leadId } : {}), ...(input.opportunityId ? { opportunityId: input.opportunityId } : {}), currentState: state, ...(input.previous ? { previousState: input.previous.currentState } : {}), reasonCodes: reasons, evidenceRefs: evidence(events), confidence: events.length ? 0.85 : 0, effectiveAt: at, freshness: events.length ? 'FRESH' : 'UNKNOWN', limitations: events.length ? [] : ['MISSING_JOURNEY_EVIDENCE'] };
}

export function validLifecycleTransition(from: CustomerLifecycleState, to: CustomerLifecycleState): boolean {
  if (from === to || from === 'UNKNOWN' || to === 'UNKNOWN') return true;
  if (to === 'CHURNED') return ['CUSTOMER', 'ACTIVE_CUSTOMER', 'AT_RISK', 'DORMANT', 'RENEWAL_DUE'].includes(from);
  if (to === 'DORMANT') return ['LEAD', 'ENGAGED_LEAD', 'QUALIFIED_LEAD', 'OPPORTUNITY', 'CUSTOMER', 'ACTIVE_CUSTOMER', 'AT_RISK', 'RENEWAL_DUE'].includes(from);
  if (to === 'AT_RISK' || to === 'RENEWAL_DUE' || to === 'EXPANSION_CANDIDATE' || to === 'ADVOCATE') return ['CUSTOMER', 'ACTIVE_CUSTOMER', 'DORMANT', 'RENEWAL_DUE', 'AT_RISK'].includes(from);
  return true;
}

export function orderJourneyEvents(events: CustomerJourneyEvent[]): CustomerJourneyEvent[] { return clone(events).sort((a, b) => a.occurredAt.localeCompare(b.occurredAt) || a.eventId.localeCompare(b.eventId)); }
export function assessJourneyStage(lifecycle: CustomerLifecycleAssessment, events: CustomerJourneyEvent[], now = new Date().toISOString()): JourneyStageAssessment {
  const ordered = orderJourneyEvents(events); const entry = [...ordered].reverse().find((event) => event.occurredAt <= lifecycle.effectiveAt)?.occurredAt;
  const current = new Date(now).getTime(); const entered = entry ? new Date(entry).getTime() : undefined;
  const progression = ordered.filter((event) => ['QUALIFIED', 'OPPORTUNITY_CREATED', 'OPPORTUNITY_ADVANCED', 'CLOSED_WON', 'REVENUE_VERIFIED'].includes(event.type));
  const regression = ordered.filter((event) => ['DORMANCY_SIGNAL', 'COMPLAINT', 'SUPPORT_ESCALATION', 'CHURN_SIGNAL'].includes(event.type));
  return { assessmentId: hash('stage', [lifecycle.assessmentId, lifecycle.currentState, entry]), tenantId: lifecycle.tenantId, identityId: lifecycle.identityId, currentState: lifecycle.currentState, ...(lifecycle.previousState ? { previousState: lifecycle.previousState } : {}), ...(entry ? { stageEntryAt: entry, timeInStageMs: Math.max(0, current - (entered ?? current)) } : {}), progressionEvidence: evidence(progression), regressionEvidence: evidence(regression), blockers: lifecycle.currentState === 'UNKNOWN' ? ['INSUFFICIENT_EVIDENCE'] : [], unknowns: lifecycle.currentState === 'UNKNOWN' ? ['LIFECYCLE_UNKNOWN'] : [], staleness: ordered.length ? 'FRESH' : 'UNKNOWN', confidence: lifecycle.confidence, assessedAt: now };
}

export function assessActionEligibility(input: { tenantId: string; identityId?: string; action: JourneyAction; lifecycle: CustomerLifecycleState; contactability?: ContactabilityAssessment; capabilities: JourneyCapability[]; frequency?: ContactFrequencyAssessment; evidenceRefs: ConversationEvidenceRef[]; unresolvedHandoff?: boolean; duplicate?: boolean; policyRequiresApproval?: boolean; now?: string }): ActionEligibilityAssessment {
  const reasons: string[] = []; const outbound = isOutbound(input.action); let result: EligibilityResult = 'ELIGIBLE';
  if (!input.identityId) { result = 'INSUFFICIENT_EVIDENCE'; reasons.push('MISSING_IDENTITY'); }
  if (outbound && (!input.contactability || input.contactability.status === 'UNKNOWN')) { result = 'INSUFFICIENT_EVIDENCE'; reasons.push('MISSING_CONTACTABILITY_EVIDENCE'); }
  if (outbound && ['OPTED_OUT', 'BLOCKED', 'RESTRICTED'].includes(input.contactability?.status ?? 'UNKNOWN')) { result = 'BLOCKED'; reasons.push('CONTACTABILITY_BLOCKED'); }
  if (input.frequency && input.frequency.result !== 'OK') { result = input.frequency.result === 'COOLDOWN' ? 'BLOCKED' : 'INSUFFICIENT_EVIDENCE'; reasons.push(`FREQUENCY_${input.frequency.result}`); }
  if (input.duplicate) { result = 'BLOCKED'; reasons.push('DUPLICATE_RECOMMENDATION'); }
  if (input.unresolvedHandoff && ['HANDOFF_SALES', 'HANDOFF_SUPPORT', 'OFFER_MEETING'].includes(input.action)) { result = 'BLOCKED'; reasons.push('UNRESOLVED_HANDOFF'); }
  if (outbound && input.capabilities.length === 0) { result = 'INELIGIBLE'; reasons.push('PROVIDER_CAPABILITY_UNAVAILABLE'); }
  if (input.policyRequiresApproval && result === 'ELIGIBLE') { result = 'REQUIRES_APPROVAL'; reasons.push('POLICY_APPROVAL_REQUIRED'); }
  if (!input.evidenceRefs.length && result === 'ELIGIBLE') { result = 'INSUFFICIENT_EVIDENCE'; reasons.push('MISSING_EVIDENCE'); }
  return { assessmentId: hash('eligibility', [input.tenantId, input.identityId, input.action, result, reasons]), tenantId: input.tenantId, identityId: input.identityId ?? 'UNKNOWN', action: input.action, result, reasonCodes: reasons.length ? reasons : ['ELIGIBLE_EVIDENCE_BACKED_ACTION'], evidenceRefs: clone(input.evidenceRefs), requiredConsent: outbound, requiredPolicy: true, requiredApproval: Boolean(input.policyRequiresApproval), eligibleCapabilities: clone(input.capabilities), limitations: result === 'ELIGIBLE' ? ['RECOMMENDATION_ONLY_NO_PROVIDER_EXECUTION'] : ['FAIL_CLOSED'], assessedAt: input.now ?? new Date().toISOString() };
}

export function generateNextBestActions(input: { lifecycle: CustomerLifecycleAssessment; events: CustomerJourneyEvent[]; contactability?: ContactabilityAssessment; capabilities: JourneyCapability[]; frequency?: ContactFrequencyAssessment; now?: string }): NextBestActionRecommendation[] {
  const now = input.now ?? new Date().toISOString(); const eventTypes = new Set(input.events.map((event) => event.type));
  let candidates: JourneyAction[] = ['NO_ACTION'];
  if (input.contactability?.status === 'OPTED_OUT' || eventTypes.has('OPT_OUT')) candidates = ['DO_NOT_CONTACT'];
  else if (eventTypes.has('COMPLAINT') || eventTypes.has('SUPPORT_ESCALATION')) candidates = ['ESCALATE', 'HANDOFF_SUPPORT'];
  else if (input.lifecycle.currentState === 'RENEWAL_DUE') candidates = ['RENEWAL_OUTREACH', 'HANDOFF_SALES'];
  else if (input.lifecycle.currentState === 'EXPANSION_CANDIDATE') candidates = ['EXPANSION_OUTREACH', 'HANDOFF_SALES'];
  else if (input.lifecycle.currentState === 'DORMANT') candidates = ['REENGAGE', 'NO_ACTION'];
  else if (input.lifecycle.currentState === 'QUALIFIED_LEAD' && !input.lifecycle.opportunityId) candidates = ['CREATE_OPPORTUNITY_RECOMMENDATION', 'HANDOFF_SALES'];
  else if (eventTypes.has('MEETING_REQUESTED')) candidates = ['OFFER_MEETING', 'HANDOFF_SALES'];
  else if (input.lifecycle.currentState === 'ENGAGED_LEAD') candidates = ['QUALIFY', 'FOLLOW_UP'];
  const refs = evidence(input.events); return candidates.map((action): NextBestActionRecommendation => {
    const eligibility = assessActionEligibility({ tenantId: input.lifecycle.tenantId, identityId: input.lifecycle.identityId, action, lifecycle: input.lifecycle.currentState, ...(input.contactability ? { contactability: input.contactability } : {}), capabilities: input.capabilities, ...(input.frequency ? { frequency: input.frequency } : {}), evidenceRefs: refs, now });
    const priority: NextBestActionRecommendation['priority'] = action === 'ESCALATE' || action === 'DO_NOT_CONTACT' ? 'URGENT' : action.includes('HANDOFF') || action.includes('RENEWAL') ? 'HIGH' : 'NORMAL';
    return { recommendationId: hash('nba', [input.lifecycle.tenantId, input.lifecycle.identityId, action, input.lifecycle.effectiveAt]), deterministicKey: hash('nba-key', [input.lifecycle.tenantId, input.lifecycle.identityId, action, input.lifecycle.effectiveAt]), tenantId: input.lifecycle.tenantId, identityId: input.lifecycle.identityId, lifecycleState: input.lifecycle.currentState, action, reasonCodes: [...input.lifecycle.reasonCodes, ...eligibility.reasonCodes], evidenceRefs: refs, confidence: eligibility.result === 'ELIGIBLE' ? input.lifecycle.confidence : 0, priority, expectedOutcome: `GOVERNED_${action}`, eligibleCapabilities: eligibility.eligibleCapabilities, requiredConsent: eligibility.requiredConsent, requiredPolicy: true, requiredApproval: eligibility.requiredApproval, eligibility: eligibility.result, expiresAt: new Date(new Date(now).getTime() + 86_400_000).toISOString(), tradeoffs: ['NO_AUTONOMOUS_EXECUTION', 'EVIDENCE_AND_POLICY_REQUIRED'], limitations: eligibility.limitations, state: 'RECOMMENDATION_ONLY', createdAt: now };
  }).sort((a, b) => priorityWeight(b.priority) - priorityWeight(a.priority) || a.action.localeCompare(b.action)).map((item, index) => ({ ...item, rank: index + 1 }));
}
function priorityWeight(value: NextBestActionRecommendation['priority']): number { return ({ LOW: 1, NORMAL: 2, HIGH: 3, URGENT: 4 })[value]; }
export function buildJourneyPlan(recommendations: NextBestActionRecommendation[], now = new Date().toISOString()): CustomerJourneyPlan {
  const first = recommendations[0]; if (!first) throw new Error('JOURNEY_PLAN_REQUIRES_RECOMMENDATION');
  const actionable = recommendations.filter((item) => item.eligibility === 'ELIGIBLE' || item.eligibility === 'REQUIRES_APPROVAL');
  return { planId: hash('journey-plan', [first.tenantId, first.identityId, recommendations.map((item) => item.deterministicKey)]), tenantId: first.tenantId, identityId: first.identityId, lifecycleState: first.lifecycleState, steps: actionable.map((item, index) => ({ sequence: index + 1, action: item.action, trigger: item.reasonCodes.join(','), timing: 'NEXT_ELIGIBLE_WINDOW', eligibleCapabilities: item.eligibleCapabilities, requiredEvidence: item.evidenceRefs.map((ref) => ref.id), consentRequired: item.requiredConsent, policyRequired: item.requiredPolicy, approvalRequired: item.requiredApproval, expiresAt: item.expiresAt, status: item.eligibility === 'ELIGIBLE' ? 'ELIGIBLE' : 'PLANNED' })), state: 'RECOMMENDATION_ONLY', createdAt: now, limitations: ['NO_PROVIDER_EXECUTION'] };
}
export function assessRetentionRisk(tenantId: string, identityId: string, events: CustomerJourneyEvent[], now = new Date().toISOString()): RetentionRiskAssessment { const high = events.filter((event) => ['COMPLAINT', 'SUPPORT_ESCALATION', 'CHURN_SIGNAL'].includes(event.type)); const medium = events.filter((event) => ['DORMANCY_SIGNAL', 'RENEWAL_SIGNAL'].includes(event.type)); return { tenantId, identityId, level: high.length ? 'HIGH' : medium.length ? 'MEDIUM' : events.length ? 'LOW' : 'INSUFFICIENT_DATA', reasonCodes: high.length ? high.map((event) => event.type) : medium.length ? medium.map((event) => event.type) : ['NO_RISK_SIGNAL'], evidenceRefs: evidence(high.length ? high : medium), limitations: ['DETERMINISTIC_SIGNALS_ONLY_NOT_PREDICTIVE_ML'], assessedAt: now }; }
export function assessExpansion(tenantId: string, identityId: string, events: CustomerJourneyEvent[]): ExpansionOpportunityAssessment { const signals = events.filter((event) => event.type === 'EXPANSION_SIGNAL'); return { tenantId, identityId, strength: signals.length ? 'STRONG' : events.length ? 'NONE' : 'INSUFFICIENT_DATA', reasonCodes: signals.length ? ['EXPLICIT_EXPANSION_SIGNAL'] : ['NO_EXPANSION_EVIDENCE'], evidenceRefs: evidence(signals), recommendation: signals.length ? 'EXPANSION_OUTREACH' : 'NO_ACTION', limitations: ['RECOMMENDATION_ONLY_NO_PIPELINE_OR_REVENUE_CREATED'] }; }
export function assessHealth(tenantId: string, identityId: string, events: CustomerJourneyEvent[]): CustomerHealthAssessment { const risk = assessRetentionRisk(tenantId, identityId, events); const health = risk.level === 'HIGH' ? 'AT_RISK' : risk.level === 'MEDIUM' ? 'WATCH' : risk.level === 'LOW' ? 'HEALTHY' : 'INSUFFICIENT_DATA'; return { tenantId, identityId, health, dimensions: { engagement: events.length ? 'POSITIVE' : 'UNKNOWN', issues: risk.level === 'HIGH' ? 'CONCERN' : 'NEUTRAL', renewal: has(events, 'RENEWAL_SIGNAL').length ? 'NEUTRAL' : 'UNKNOWN' }, reasonCodes: risk.reasonCodes, evidenceRefs: risk.evidenceRefs, limitations: risk.limitations }; }
export function assessRenewal(tenantId: string, identityId: string, lifecycle: CustomerLifecycleState, events: CustomerJourneyEvent[], renewalDate?: string): RenewalAssessment { const signal = has(events, 'RENEWAL_SIGNAL'); const due = lifecycle === 'RENEWAL_DUE' || Boolean(signal.length); return { tenantId, identityId, ...(renewalDate ? { renewalDate } : {}), renewalWindow: due ? 'DUE' : renewalDate ? 'UPCOMING' : 'UNKNOWN', customerStatus: lifecycle, recommendation: due ? 'RENEWAL_OUTREACH' : 'NO_ACTION', handoffRecommended: due, evidenceRefs: evidence(signal), limitations: renewalDate ? [] : ['RENEWAL_DATE_UNKNOWN_NOT_INFERRED'] }; }
export function assessReengagement(tenantId: string, identityId: string, lifecycle: CustomerLifecycleState, events: CustomerJourneyEvent[], contactability?: ContactabilityAssessment) { const last = orderJourneyEvents(events).at(-1); const dormant = lifecycle === 'DORMANT' && has(events, 'DORMANCY_SIGNAL').length > 0; return { tenantId, identityId, dormant, ...(last ? { lastMeaningfulEngagementAt: last.occurredAt } : {}), previousIntent: 'UNKNOWN', contactability: contactability?.status ?? 'UNKNOWN', recommendation: dormant && contactability?.status === 'ALLOWED' ? 'REENGAGE' as JourneyAction : 'NO_ACTION' as JourneyAction, evidenceRefs: evidence(events), limitations: dormant ? [] : ['DORMANCY_REQUIRES_EVIDENCE_NOT_LOW_VOLUME'] }; }
export function assessContactFrequency(tenantId: string, identityId: string, recentAttempts: number, recentResponses: number, contactability?: ContactabilityAssessment): ContactFrequencyAssessment { const blocked = ['OPTED_OUT', 'BLOCKED', 'RESTRICTED'].includes(contactability?.status ?? 'UNKNOWN'); const cooldown = recentAttempts >= 3 && recentResponses === 0; return { tenantId, identityId, purpose: contactability?.purpose ?? 'UNKNOWN', result: blocked ? 'BLOCKED' : cooldown ? 'COOLDOWN' : contactability ? 'OK' : 'INSUFFICIENT_DATA', recentAttempts, recentResponses, ...(cooldown ? { cooldownUntil: new Date(Date.now() + 86_400_000).toISOString() } : {}), reasonCodes: blocked ? ['CONTACTABILITY_BLOCKED'] : cooldown ? ['UNANSWERED_ATTEMPT_COOLDOWN'] : contactability ? ['CONTACT_FREQUENCY_OK'] : ['MISSING_CONTACTABILITY_EVIDENCE'] }; }
export function diagnoseJourneyBlockers(lifecycle: CustomerLifecycleAssessment, events: CustomerJourneyEvent[], contactability?: ContactabilityAssessment): JourneyBlockerDiagnostic[] { const common = { tenantId: lifecycle.tenantId, identityId: lifecycle.identityId, evidenceRefs: evidence(events), limitations: ['DIAGNOSTIC_ONLY_NO_EXECUTION'], generatedAt: new Date().toISOString() }; const make = (type: JourneyBlockerDiagnostic['type'], severity: JourneyBlockerDiagnostic['severity'], action: JourneyAction): JourneyBlockerDiagnostic => ({ diagnosticId: hash('journey-blocker', [lifecycle.tenantId, lifecycle.identityId, type, lifecycle.effectiveAt]), ...common, type, severity, reasonCodes: [type], recommendedNextStep: action }); if (contactability?.status === 'OPTED_OUT') return [make('OPTED_OUT', 'HIGH', 'DO_NOT_CONTACT')]; if (lifecycle.currentState === 'UNKNOWN') return [make('INSUFFICIENT_EVIDENCE', 'WARNING', 'ASK_CLARIFYING_QUESTION')]; if (lifecycle.currentState === 'QUALIFIED_LEAD' && !lifecycle.opportunityId) return [make('QUALIFIED_NO_OPPORTUNITY', 'WARNING', 'CREATE_OPPORTUNITY_RECOMMENDATION')]; if (lifecycle.currentState === 'AT_RISK') return [make('CUSTOMER_AT_RISK', 'HIGH', 'ESCALATE')]; return []; }
export function buildJourneyContextFromEvents(base: CustomerJourneyContext, events: CustomerJourneyEvent[]): CustomerJourneyContext { return { ...clone(base), evidenceRefs: [...base.evidenceRefs, ...evidence(events)] }; }
export function triggersFromEvents(events: CustomerJourneyEvent[]): JourneyTrigger[] { const mappings: Partial<Record<JourneyEventType, JourneyTrigger['type']>> = { LEAD_CREATED: 'NEW_LEAD', CUSTOMER_REPLIED: 'CUSTOMER_REPLIED', HIGH_INTENT_SIGNAL: 'HIGH_INTENT', MEETING_REQUESTED: 'MEETING_REQUESTED', DORMANCY_SIGNAL: 'CUSTOMER_DORMANT', RENEWAL_SIGNAL: 'RENEWAL_WINDOW', EXPANSION_SIGNAL: 'EXPANSION_SIGNAL', COMPLAINT: 'COMPLAINT', OPT_OUT: 'OPT_OUT', REVENUE_VERIFIED: 'REVENUE_VERIFIED', CHURN_SIGNAL: 'CHURN_RISK_SIGNAL' }; return events.flatMap((event) => { const type = mappings[event.type]; return type && event.identityId ? [{ triggerId: hash('journey-trigger', [event.tenantId, event.identityId, type, event.eventId]), tenantId: event.tenantId, identityId: event.identityId, type, deterministicKey: hash('trigger-key', [event.tenantId, event.identityId, type, event.eventId]), evidenceRefs: clone(event.evidenceRefs), occurredAt: event.occurredAt }] : []; }); }
