import { createHash } from 'node:crypto';
export type GrowthObjective = 'ACQUIRE'|'ENGAGE'|'QUALIFY'|'CONVERT'|'RETAIN'|'RENEW'|'EXPAND'|'REENGAGE'|'RECOVER'|'ADVOCATE'; export type GrowthRecommendationState='GENERATED'|'ELIGIBLE'|'INELIGIBLE'|'RANKED'|'RECOMMENDED'|'DEFERRED'|'SUPPRESSED'|'HUMAN_REVIEW_REQUIRED'|'EXPIRED'|'SUPERSEDED';
export interface GrowthDecisionContext { tenantId:string; identityId:string; lifecycleState:string; objective:GrowthObjective; consent:'GRANTED'|'DENIED'|'UNKNOWN'; contactable:boolean|undefined; capabilities:string[]; evidenceRefs:string[]; evidenceFresh:boolean; recentContactCount:number; humanHandoff?:boolean; complaint?:boolean; pendingActivation?:boolean; }
export interface GrowthActionCandidate { id:string; objective:GrowthObjective; actionType:string; state:GrowthRecommendationState; reasons:string[]; evidenceRefs:string[]; }
export interface GrowthDecisionConflictAssessment { conflict:boolean; reasons:string[]; }
export interface GrowthDecisionScore { total:number; components:Record<string,number>; }
const hash=(value:string)=>createHash('sha256').update(value).digest('hex').slice(0,32);
export function assessGrowthEligibility(context:GrowthDecisionContext):{eligible:boolean;reasons:string[]}{const reasons:string[]=[];if(context.consent!=='GRANTED')reasons.push('CONSENT_UNAVAILABLE_OR_DENIED');if(!context.contactable)reasons.push('CONTACTABILITY_UNAVAILABLE');if(!context.capabilities.length)reasons.push('CAPABILITY_UNAVAILABLE');if(!context.evidenceFresh)reasons.push('STALE_EVIDENCE');if(context.recentContactCount>=3)reasons.push('FREQUENCY_CAP');if(context.humanHandoff)reasons.push('UNRESOLVED_HUMAN_HANDOFF');if(context.pendingActivation)reasons.push('PENDING_ACTIVATION');return{eligible:!reasons.length,reasons};}
export function assessGrowthConflict(context:GrowthDecisionContext,candidate:GrowthActionCandidate):GrowthDecisionConflictAssessment{const reasons:string[]=[];if(context.complaint&&candidate.actionType==='PROMOTIONAL_ACTIVATION')reasons.push('UNRESOLVED_COMPLAINT_PROMOTIONAL_CONFLICT');if(context.lifecycleState==='AT_RISK'&&candidate.objective==='EXPAND')reasons.push('CHURN_RISK_UPSELL_CONFLICT');if(context.humanHandoff)reasons.push('HUMAN_HANDOFF_AUTOMATION_CONFLICT');return{conflict:!!reasons.length,reasons};}
export function scoreGrowthCandidate(context:GrowthDecisionContext,candidate:GrowthActionCandidate):GrowthDecisionScore{const components={objective:20,lifecycle:context.lifecycleState==='AT_RISK'&&candidate.objective==='RETAIN'?30:10,evidence:context.evidenceRefs.length?20:0,freshness:context.evidenceFresh?10:0,frequency:context.recentContactCount?-context.recentContactCount*5:0};return{components,total:Object.values(components).reduce((a,b)=>a+b,0)};}
export function decideGrowth(context:GrowthDecisionContext):{candidate:GrowthActionCandidate;eligibility:{eligible:boolean;reasons:string[]};conflict:GrowthDecisionConflictAssessment;score:GrowthDecisionScore}{const actionType=context.objective==='RETAIN'?'RETENTION_INTERVENTION':context.objective==='EXPAND'?'EXPANSION_RECOMMENDATION':'LIFECYCLE_ACTIVATION_RECOMMENDATION';const candidate={id:hash(`${context.tenantId}:${context.identityId}:${context.objective}:${actionType}`),objective:context.objective,actionType,state:'GENERATED' as GrowthRecommendationState,reasons:['DETERMINISTIC_CONTEXT_MATCH'],evidenceRefs:[...context.evidenceRefs]};const eligibility=assessGrowthEligibility(context);const conflict=assessGrowthConflict(context,candidate);candidate.state=!eligibility.eligible?'INELIGIBLE':conflict.conflict?'HUMAN_REVIEW_REQUIRED':'RECOMMENDED';return{candidate,eligibility,conflict,score:scoreGrowthCandidate(context,candidate)};}
