import { createHash } from 'node:crypto';

export const activationChannels = ['EMAIL', 'SMS', 'WHATSAPP', 'CRM_TASK', 'CRM_STAGE_RECOMMENDATION', 'MEETING_FOLLOW_UP', 'AD_AUDIENCE', 'PAID_MEDIA', 'IN_APP', 'WEB_PERSONALIZATION', 'REPUTATION_REVIEW_REQUEST'] as const;
export type ActivationChannel = typeof activationChannels[number];
export type ActivationState = 'PROPOSED' | 'ELIGIBLE' | 'SIMULATED' | 'AWAITING_APPROVAL' | 'APPROVED' | 'EXECUTION_PENDING' | 'EXECUTED_UNVERIFIED' | 'VERIFIED' | 'FAILED' | 'UNCERTAIN' | 'SUPPRESSED' | 'EXPIRED' | 'CANCELLED';
export type ActivationOutcome = 'IMPROVED' | 'DEGRADED' | 'NEUTRAL' | 'UNKNOWN';
export interface ActivationCandidate { candidateId: string; tenantId: string; identityId: string; nextBestActionId: string; channel: ActivationChannel; state: ActivationState; idempotencyKey: string; evidenceRefs: string[]; reasons: string[]; }
export interface LifecycleActivationStep { stepId: string; sequence: number; candidateId: string; state: ActivationState; }
export interface LifecycleActivationPlan { planId: string; tenantId: string; identityId: string; nextBestActionId: string; idempotencyKey: string; state: ActivationState; steps: LifecycleActivationStep[]; limitations: string[]; }
export interface ActivationEligibilityAssessment { eligible: boolean; reasons: string[]; assessedAt: string; }
export interface ActivationImpactSimulation { objective: string; channel: ActivationChannel; expectedOperationalEffect: string; potentialDownside: string[]; budgetImpact?: number; contactFrequencyImpact: string; assumptions: string[]; limitations: string[]; confidence: number; evidenceRefs: string[]; }
export interface ActivationPolicyAssessment { allowed: boolean; requiresApproval: true; reasons: string[]; }
export interface ActivationApprovalReference { approvalId: string; status: 'PENDING' | 'APPROVED' | 'REJECTED' | 'EXPIRED'; }
export interface ActivationExecutionRequest { requestId: string; candidateId: string; state: 'EXECUTION_PENDING'; idempotencyKey: string; governedExternalActionId?: string; }
export interface ActivationExecutionReference { executionId: string; state: 'EXECUTED_UNVERIFIED' | 'UNCERTAIN' | 'FAILED'; providerReference?: string; }
export interface ActivationVerification { verificationId: string; executionId: string; state: 'VERIFIED' | 'FAILED' | 'UNCERTAIN'; evidenceRefs: string[]; limitations: string[]; }
export interface ActivationLearningLink { outcomeId: string; journeyOutcomeId?: string; journeyLearningId?: string; causalClaim: 'NONE'; }
export interface ActivationSuppression { suppressed: boolean; reasons: string[]; }
export interface ActivationFrequencyDecision { allowed: boolean; reasons: string[]; }
export interface ActivationConflictAssessment { conflict: boolean; reasons: string[]; evidenceRefs: string[]; }
export interface ActivationInput { tenantId: string; identityId: string; nextBestActionId: string; lifecycleState: string; channelAvailability: Partial<Record<ActivationChannel, boolean>>; consent: 'GRANTED' | 'DENIED' | 'UNKNOWN'; contactable: boolean | undefined; recentContactCount: number; activeSuppression?: boolean; conflictingAction?: boolean; nbaExpiresAt: string; now: string; evidenceRefs: string[]; }
const id = (seed: string) => createHash('sha256').update(seed).digest('hex').slice(0, 32);
export function selectActivationChannel(input: ActivationInput): ActivationChannel | undefined { for (const channel of ['EMAIL', 'SMS', 'WHATSAPP', 'CRM_TASK', 'IN_APP'] as ActivationChannel[]) if (input.channelAvailability[channel]) return channel; return undefined; }
export function assessActivationEligibility(input: ActivationInput): ActivationEligibilityAssessment { const reasons: string[] = []; if (input.consent !== 'GRANTED') reasons.push('CONSENT_UNAVAILABLE_OR_DENIED'); if (!input.contactable) reasons.push('CONTACTABILITY_UNAVAILABLE'); if (!selectActivationChannel(input)) reasons.push('CHANNEL_UNAVAILABLE'); if (input.activeSuppression) reasons.push('ACTIVE_SUPPRESSION'); if (input.recentContactCount >= 3) reasons.push('FREQUENCY_CAP'); if (input.conflictingAction) reasons.push('CONFLICTING_JOURNEY_ACTION'); if (Date.parse(input.nbaExpiresAt) <= Date.parse(input.now)) reasons.push('STALE_OR_EXPIRED_NBA'); return { eligible: reasons.length === 0, reasons, assessedAt: input.now }; }
export function assessActivationConflict(input: ActivationInput): ActivationConflictAssessment { const reasons = input.conflictingAction ? ['CONTRADICTORY_OR_DUPLICATE_LIFECYCLE_ACTION'] : []; return { conflict: reasons.length > 0, reasons, evidenceRefs: [...input.evidenceRefs] }; }
export function buildLifecycleActivationPlan(input: ActivationInput): { plan: LifecycleActivationPlan; candidate: ActivationCandidate; eligibility: ActivationEligibilityAssessment; simulation: ActivationImpactSimulation; policy: ActivationPolicyAssessment; suppression: ActivationSuppression; frequency: ActivationFrequencyDecision; conflict: ActivationConflictAssessment } { const channel = selectActivationChannel(input) ?? 'CRM_TASK'; const eligibility = assessActivationEligibility(input); const conflict = assessActivationConflict(input); const candidateId = id(`${input.tenantId}:${input.identityId}:${input.nextBestActionId}:${channel}`); const state: ActivationState = eligibility.eligible ? 'AWAITING_APPROVAL' : eligibility.reasons.includes('STALE_OR_EXPIRED_NBA') ? 'EXPIRED' : 'SUPPRESSED'; const candidate = { candidateId, tenantId: input.tenantId, identityId: input.identityId, nextBestActionId: input.nextBestActionId, channel, state, idempotencyKey: `activation-candidate:${candidateId}`, evidenceRefs: [...input.evidenceRefs], reasons: eligibility.reasons }; const plan = { planId: id(`plan:${candidateId}`), tenantId: input.tenantId, identityId: input.identityId, nextBestActionId: input.nextBestActionId, idempotencyKey: `activation-plan:${candidateId}`, state, steps: [{ stepId: id(`step:${candidateId}`), sequence: 1, candidateId, state }], limitations: ['RECOMMENDATION_ONLY_UNTIL_CANONICAL_APPROVAL_AND_GOVERNED_EXECUTION'] }; return { plan, candidate, eligibility, simulation: { objective: input.lifecycleState, channel, expectedOperationalEffect: 'PROVIDER_NEUTRAL_RECOMMENDATION_ONLY', potentialDownside: ['UNVERIFIED_OUTCOME', 'CONTACT_FREQUENCY'], contactFrequencyImpact: input.recentContactCount ? 'INCREASES_RECENT_CONTACT_LOAD' : 'FIRST_KNOWN_CONTACT', assumptions: ['NO_CAUSAL_LIFT_CLAIM'], limitations: ['INDEPENDENT_VERIFICATION_REQUIRED'], confidence: input.evidenceRefs.length ? 0.5 : 0, evidenceRefs: [...input.evidenceRefs] }, policy: { allowed: eligibility.eligible && !conflict.conflict, requiresApproval: true, reasons: conflict.reasons }, suppression: { suppressed: !eligibility.eligible, reasons: eligibility.reasons }, frequency: { allowed: input.recentContactCount < 3, reasons: input.recentContactCount < 3 ? [] : ['FREQUENCY_CAP'] }, conflict }; }
