import { and, asc, eq } from 'drizzle-orm';

import type { TenantContext } from '@platform/contracts';
import { customerJourneyEvents, customerJourneyPlans, customerJourneyStageAssessments, customerLifecycleAssessments, journeyActionOutcomes, journeyLearningRecords, nextBestActionRecommendations } from '@platform/db';
import type { CustomerJourneyEvent, CustomerJourneyPlan, CustomerLifecycleAssessment, JourneyActionOutcome, JourneyLearningRecord, JourneyStageAssessment, NextBestActionRecommendation } from '@platform/marketing-os-core';
import type { MarketingOSPersistenceDatabase } from './index.js';

const copy = <T>(value: T): T => structuredClone(value);
function assertTenant(context: TenantContext, tenantId?: string): asserts context is TenantContext & { tenantId: string } { if (!context.tenantId || (tenantId && tenantId !== context.tenantId)) throw new Error('TENANT_SCOPE_DENIED'); }

/** Durable EPIC11 evidence/recommendation store. Every read carries tenant scope; RLS is the database boundary. */
export class PersistentCustomerJourneyStore {
  constructor(private readonly db: MarketingOSPersistenceDatabase) {}
  async saveEvent(context: TenantContext, event: CustomerJourneyEvent): Promise<CustomerJourneyEvent> { assertTenant(context, event.tenantId); await this.db.insert(customerJourneyEvents).values({ id: event.eventId, tenantId: event.tenantId, identityId: event.identityId ?? null, leadId: event.leadId ?? null, eventType: event.type, idempotencyKey: event.idempotencyKey, event, occurredAt: new Date(event.occurredAt), createdAt: new Date(), updatedAt: new Date() }).onConflictDoNothing(); const saved = await this.findEvent(context, event.idempotencyKey); if (!saved) throw new Error('JOURNEY_EVENT_SAVE_FAILED'); if (saved.eventId !== event.eventId) throw new Error('JOURNEY_EVENT_IDEMPOTENCY_MISMATCH'); return saved; }
  async findEvent(context: TenantContext, idempotencyKey: string): Promise<CustomerJourneyEvent | undefined> { assertTenant(context); const [row] = await this.db.select().from(customerJourneyEvents).where(and(eq(customerJourneyEvents.tenantId, context.tenantId), eq(customerJourneyEvents.idempotencyKey, idempotencyKey))).limit(1); return row ? copy(row.event as CustomerJourneyEvent) : undefined; }
  async listEvents(context: TenantContext, identityId: string): Promise<CustomerJourneyEvent[]> { assertTenant(context); const rows = await this.db.select().from(customerJourneyEvents).where(and(eq(customerJourneyEvents.tenantId, context.tenantId), eq(customerJourneyEvents.identityId, identityId))).orderBy(asc(customerJourneyEvents.occurredAt)); return rows.map((row) => copy(row.event as CustomerJourneyEvent)); }
  async saveLifecycle(context: TenantContext, assessment: CustomerLifecycleAssessment): Promise<CustomerLifecycleAssessment> { assertTenant(context, assessment.tenantId); await this.db.insert(customerLifecycleAssessments).values({ id: assessment.assessmentId, tenantId: assessment.tenantId, identityId: assessment.identityId, leadId: assessment.leadId ?? null, opportunityId: assessment.opportunityId ?? null, currentState: assessment.currentState, previousState: assessment.previousState ?? null, assessment, effectiveAt: new Date(assessment.effectiveAt), createdAt: new Date(), updatedAt: new Date() }).onConflictDoUpdate({ target: [customerLifecycleAssessments.tenantId, customerLifecycleAssessments.identityId], set: { currentState: assessment.currentState, previousState: assessment.previousState ?? null, assessment, effectiveAt: new Date(assessment.effectiveAt), updatedAt: new Date() } }); return copy(assessment); }
  async getLifecycle(context: TenantContext, identityId: string): Promise<CustomerLifecycleAssessment | undefined> { assertTenant(context); const [row] = await this.db.select().from(customerLifecycleAssessments).where(and(eq(customerLifecycleAssessments.tenantId, context.tenantId), eq(customerLifecycleAssessments.identityId, identityId))).limit(1); return row ? copy(row.assessment as CustomerLifecycleAssessment) : undefined; }
  async saveStage(context: TenantContext, assessment: JourneyStageAssessment): Promise<JourneyStageAssessment> { assertTenant(context, assessment.tenantId); await this.db.insert(customerJourneyStageAssessments).values({ id: assessment.assessmentId, tenantId: assessment.tenantId, identityId: assessment.identityId, currentState: assessment.currentState, assessment, assessedAt: new Date(assessment.assessedAt), createdAt: new Date(), updatedAt: new Date() }).onConflictDoUpdate({ target: [customerJourneyStageAssessments.tenantId, customerJourneyStageAssessments.identityId], set: { currentState: assessment.currentState, assessment, assessedAt: new Date(assessment.assessedAt), updatedAt: new Date() } }); return copy(assessment); }
  async getStage(context: TenantContext, identityId: string): Promise<JourneyStageAssessment | undefined> { assertTenant(context); const [row] = await this.db.select().from(customerJourneyStageAssessments).where(and(eq(customerJourneyStageAssessments.tenantId, context.tenantId), eq(customerJourneyStageAssessments.identityId, identityId))).limit(1); return row ? copy(row.assessment as JourneyStageAssessment) : undefined; }
  async saveRecommendation(context: TenantContext, recommendation: NextBestActionRecommendation): Promise<NextBestActionRecommendation> { assertTenant(context, recommendation.tenantId); await this.db.insert(nextBestActionRecommendations).values({ id: recommendation.recommendationId, tenantId: recommendation.tenantId, identityId: recommendation.identityId, action: recommendation.action, deterministicKey: recommendation.deterministicKey, eligibility: recommendation.eligibility, expiresAt: new Date(recommendation.expiresAt), recommendation, createdAt: new Date(recommendation.createdAt), updatedAt: new Date(recommendation.createdAt) }).onConflictDoNothing(); const saved = await this.findRecommendation(context, recommendation.deterministicKey); if (!saved) throw new Error('NEXT_BEST_ACTION_SAVE_FAILED'); return saved; }
  async findRecommendation(context: TenantContext, deterministicKey: string): Promise<NextBestActionRecommendation | undefined> { assertTenant(context); const [row] = await this.db.select().from(nextBestActionRecommendations).where(and(eq(nextBestActionRecommendations.tenantId, context.tenantId), eq(nextBestActionRecommendations.deterministicKey, deterministicKey))).limit(1); return row ? copy(row.recommendation as NextBestActionRecommendation) : undefined; }
  async listRecommendations(context: TenantContext, identityId: string): Promise<NextBestActionRecommendation[]> { assertTenant(context); const rows = await this.db.select().from(nextBestActionRecommendations).where(and(eq(nextBestActionRecommendations.tenantId, context.tenantId), eq(nextBestActionRecommendations.identityId, identityId))).orderBy(asc(nextBestActionRecommendations.createdAt)); return rows.map((row) => copy(row.recommendation as NextBestActionRecommendation)); }
  async savePlan(context: TenantContext, plan: CustomerJourneyPlan): Promise<CustomerJourneyPlan> { assertTenant(context, plan.tenantId); await this.db.insert(customerJourneyPlans).values({ id: plan.planId, tenantId: plan.tenantId, identityId: plan.identityId, lifecycleState: plan.lifecycleState, plan, createdAt: new Date(plan.createdAt), updatedAt: new Date(plan.createdAt) }).onConflictDoUpdate({ target: customerJourneyPlans.id, set: { lifecycleState: plan.lifecycleState, plan, updatedAt: new Date() } }); return copy(plan); }
  async getPlan(context: TenantContext, identityId: string): Promise<CustomerJourneyPlan | undefined> { assertTenant(context); const [row] = await this.db.select().from(customerJourneyPlans).where(and(eq(customerJourneyPlans.tenantId, context.tenantId), eq(customerJourneyPlans.identityId, identityId))).orderBy(asc(customerJourneyPlans.createdAt)).limit(1); return row ? copy(row.plan as CustomerJourneyPlan) : undefined; }
  async saveOutcome(context: TenantContext, outcome: JourneyActionOutcome): Promise<JourneyActionOutcome> { assertTenant(context, outcome.tenantId); await this.db.insert(journeyActionOutcomes).values({ id: outcome.outcomeId, tenantId: outcome.tenantId, identityId: outcome.identityId, idempotencyKey: outcome.idempotencyKey, outcomeType: outcome.type, outcome, observedAt: new Date(outcome.observedAt), createdAt: new Date(), updatedAt: new Date() }).onConflictDoNothing(); const [row] = await this.db.select().from(journeyActionOutcomes).where(and(eq(journeyActionOutcomes.tenantId, context.tenantId), eq(journeyActionOutcomes.idempotencyKey, outcome.idempotencyKey))).limit(1); if (!row) throw new Error('JOURNEY_OUTCOME_SAVE_FAILED'); return copy(row.outcome as JourneyActionOutcome); }
  async saveLearning(context: TenantContext, record: JourneyLearningRecord): Promise<JourneyLearningRecord> { assertTenant(context, record.tenantId); await this.db.insert(journeyLearningRecords).values({ id: record.learningId, tenantId: record.tenantId, identityId: record.identityId, learning: record, recordedAt: new Date(record.recordedAt), createdAt: new Date(), updatedAt: new Date() }).onConflictDoNothing(); return copy(record); }
  async listLearning(context: TenantContext, identityId: string): Promise<JourneyLearningRecord[]> { assertTenant(context); const rows = await this.db.select().from(journeyLearningRecords).where(and(eq(journeyLearningRecords.tenantId, context.tenantId), eq(journeyLearningRecords.identityId, identityId))).orderBy(asc(journeyLearningRecords.recordedAt)); return rows.map((row) => copy(row.learning as JourneyLearningRecord)); }
}
