import { and, asc, eq } from 'drizzle-orm';

import type { TenantContext } from '@platform/contracts';
import { aiReceptionistHandoffs, aiReceptionistSessions, conversationDiagnostics, customerConversationEvents, customerConversationIntents, customerConversationStates, customerConversationTurns, customerFollowUpRecommendations, responseRecommendations } from '@platform/db';
import type { AIReceptionistHandoff, AIReceptionistSession, ConversationDiagnostic, ConversationEventRecord, ConversationIntent, ConversationThreadRecord, ConversationTurn, CustomerEngagementStore, FollowUpRecommendation, ResponseRecommendation } from '@platform/marketing-os-core';

import type { MarketingOSPersistenceDatabase } from './index.js';

function assertTenant(context: TenantContext, tenantId?: string): asserts context is TenantContext & { tenantId: string } { if (!context.tenantId || (tenantId && tenantId !== context.tenantId)) throw new Error('TENANT_SCOPE_DENIED'); }
const copy = <T>(value: T): T => structuredClone(value);

/** Drizzle adapter for minimized, tenant-scoped conversation intelligence; it contains no transport SDK or send authority. */
export class PersistentCustomerEngagementStore implements CustomerEngagementStore {
  constructor(private readonly db: MarketingOSPersistenceDatabase) {}
  async findConversationEvent(context: TenantContext, idempotencyKey: string) { assertTenant(context); const [row] = await this.db.select().from(customerConversationEvents).where(and(eq(customerConversationEvents.tenantId, context.tenantId), eq(customerConversationEvents.idempotencyKey, idempotencyKey))).limit(1); return row ? copy(row.event as ConversationEventRecord) : undefined; }
  async saveConversationEvent(context: TenantContext, event: ConversationEventRecord) { assertTenant(context, event.tenantId); await this.db.insert(customerConversationEvents).values({ id: event.eventId, tenantId: event.tenantId, conversationId: event.conversationId, provider: event.provider, channel: event.channel, externalThreadId: event.externalThreadId ?? null, externalMessageId: event.externalMessageId ?? null, direction: event.direction, idempotencyKey: event.idempotencyKey, contentReference: event.contentReference ?? null, contentHash: event.contentHash ?? null, redactedExcerpt: event.redactedExcerpt ?? null, consentStatus: event.consentStatus, languageHints: event.languageHints, event, occurredAt: new Date(event.occurredAt), createdAt: new Date(event.createdAt), updatedAt: new Date(event.createdAt) }).onConflictDoNothing(); const persisted = await this.findConversationEvent(context, event.idempotencyKey); if (!persisted) throw new Error('CONVERSATION_EVENT_SAVE_FAILED'); if (persisted.eventId !== event.eventId) throw new Error('CONVERSATION_INGRESS_IDEMPOTENCY_MISMATCH'); return persisted; }
  async saveConversation(context: TenantContext, conversation: ConversationThreadRecord) { assertTenant(context, conversation.tenantId); await this.db.insert(customerConversationStates).values({ id: conversation.conversationId, tenantId: conversation.tenantId, conversationId: conversation.conversationId, state: conversation.state, stateRecord: conversation, updatedAt: new Date(conversation.updatedAt), createdAt: new Date(conversation.createdAt) }).onConflictDoUpdate({ target: [customerConversationStates.tenantId, customerConversationStates.conversationId], set: { state: conversation.state, stateRecord: conversation, updatedAt: new Date(conversation.updatedAt) } }); return copy(conversation); }
  async getConversation(context: TenantContext, conversationId: string) { assertTenant(context); const [row] = await this.db.select().from(customerConversationStates).where(and(eq(customerConversationStates.tenantId, context.tenantId), eq(customerConversationStates.conversationId, conversationId))).limit(1); return row ? copy(row.stateRecord as ConversationThreadRecord) : undefined; }
  async listConversations(context: TenantContext) { assertTenant(context); const rows = await this.db.select().from(customerConversationStates).where(eq(customerConversationStates.tenantId, context.tenantId)).orderBy(asc(customerConversationStates.updatedAt)); return rows.map((row) => copy(row.stateRecord as ConversationThreadRecord)); }
  async saveTurn(context: TenantContext, turn: ConversationTurn) { assertTenant(context, turn.tenantId); await this.db.insert(customerConversationTurns).values({ id: turn.turnId, tenantId: turn.tenantId, conversationId: turn.conversationId, eventId: turn.eventId, direction: turn.direction, contentReference: turn.contentReference ?? null, contentHash: turn.contentHash ?? null, redactedExcerpt: turn.redactedExcerpt ?? null, turn, occurredAt: new Date(turn.occurredAt), createdAt: new Date(turn.occurredAt), updatedAt: new Date(turn.occurredAt) }).onConflictDoNothing(); return copy(turn); }
  async listTurns(context: TenantContext, conversationId: string) { assertTenant(context); const rows = await this.db.select().from(customerConversationTurns).where(and(eq(customerConversationTurns.tenantId, context.tenantId), eq(customerConversationTurns.conversationId, conversationId))).orderBy(asc(customerConversationTurns.occurredAt)); return rows.map((row) => copy(row.turn as ConversationTurn)); }
  async saveIntent(context: TenantContext, intent: ConversationIntent) { assertTenant(context, intent.tenantId); await this.db.insert(customerConversationIntents).values({ id: intent.intentId, tenantId: intent.tenantId, conversationId: intent.conversationId, primaryIntent: intent.primary, intent, detectedAt: new Date(intent.detectedAt), createdAt: new Date(intent.detectedAt), updatedAt: new Date(intent.detectedAt) }).onConflictDoNothing(); return copy(intent); }
  async listIntents(context: TenantContext, conversationId: string) { assertTenant(context); const rows = await this.db.select().from(customerConversationIntents).where(and(eq(customerConversationIntents.tenantId, context.tenantId), eq(customerConversationIntents.conversationId, conversationId))).orderBy(asc(customerConversationIntents.detectedAt)); return rows.map((row) => copy(row.intent as ConversationIntent)); }
  async saveRecommendation(context: TenantContext, recommendation: ResponseRecommendation) { assertTenant(context, recommendation.tenantId); await this.db.insert(responseRecommendations).values({ id: recommendation.recommendationId, tenantId: recommendation.tenantId, conversationId: recommendation.conversationId, action: recommendation.action, expiresAt: new Date(recommendation.expiresAt), recommendation, createdAt: new Date(recommendation.createdAt), updatedAt: new Date(recommendation.createdAt) }).onConflictDoNothing(); return copy(recommendation); }
  async listRecommendations(context: TenantContext, conversationId: string) { assertTenant(context); const rows = await this.db.select().from(responseRecommendations).where(and(eq(responseRecommendations.tenantId, context.tenantId), eq(responseRecommendations.conversationId, conversationId))).orderBy(asc(responseRecommendations.createdAt)); return rows.map((row) => copy(row.recommendation as ResponseRecommendation)); }
  async saveSession(context: TenantContext, session: AIReceptionistSession) { assertTenant(context, session.tenantId); const idempotencyKey = session.sessionId; await this.db.insert(aiReceptionistSessions).values({ id: session.sessionId, tenantId: session.tenantId, conversationId: session.conversationId, profileId: session.profileId, state: session.state, idempotencyKey, session, createdAt: new Date(session.createdAt), updatedAt: new Date(session.updatedAt) }).onConflictDoNothing(); const persisted = await this.getSession(context, session.sessionId); if (!persisted) throw new Error('RECEPTIONIST_SESSION_SAVE_FAILED'); return persisted; }
  async getSession(context: TenantContext, sessionId: string) { assertTenant(context); const [row] = await this.db.select().from(aiReceptionistSessions).where(and(eq(aiReceptionistSessions.tenantId, context.tenantId), eq(aiReceptionistSessions.id, sessionId))).limit(1); return row ? copy(row.session as AIReceptionistSession) : undefined; }
  async saveHandoff(context: TenantContext, handoff: AIReceptionistHandoff) { assertTenant(context, handoff.tenantId); await this.db.insert(aiReceptionistHandoffs).values({ id: handoff.handoffId, tenantId: handoff.tenantId, sessionId: handoff.sessionId, target: handoff.target, status: handoff.status, handoff, createdAt: new Date(), updatedAt: new Date() }).onConflictDoNothing(); return copy(handoff); }
  async listHandoffs(context: TenantContext) { assertTenant(context); const rows = await this.db.select().from(aiReceptionistHandoffs).where(eq(aiReceptionistHandoffs.tenantId, context.tenantId)).orderBy(asc(aiReceptionistHandoffs.createdAt)); return rows.map((row) => copy(row.handoff as AIReceptionistHandoff)); }
  async saveFollowUp(context: TenantContext, recommendation: FollowUpRecommendation) { assertTenant(context, recommendation.tenantId); await this.db.insert(customerFollowUpRecommendations).values({ id: recommendation.followUpId, tenantId: recommendation.tenantId, conversationId: recommendation.conversationId, expiresAt: new Date(recommendation.expiresAt), recommendation, createdAt: new Date(), updatedAt: new Date() }).onConflictDoNothing(); return copy(recommendation); }
  async listFollowUps(context: TenantContext) { assertTenant(context); const rows = await this.db.select().from(customerFollowUpRecommendations).where(eq(customerFollowUpRecommendations.tenantId, context.tenantId)).orderBy(asc(customerFollowUpRecommendations.createdAt)); return rows.map((row) => copy(row.recommendation as FollowUpRecommendation)); }
  async saveDiagnostic(context: TenantContext, diagnostic: ConversationDiagnostic) { assertTenant(context, diagnostic.tenantId); await this.db.insert(conversationDiagnostics).values({ id: diagnostic.diagnosticId, tenantId: diagnostic.tenantId, conversationId: diagnostic.conversationId, severity: diagnostic.severity, diagnostic, generatedAt: new Date(diagnostic.generatedAt), createdAt: new Date(diagnostic.generatedAt), updatedAt: new Date(diagnostic.generatedAt) }).onConflictDoNothing(); return copy(diagnostic); }
  async listDiagnostics(context: TenantContext, conversationId: string) { assertTenant(context); const rows = await this.db.select().from(conversationDiagnostics).where(and(eq(conversationDiagnostics.tenantId, context.tenantId), eq(conversationDiagnostics.conversationId, conversationId))).orderBy(asc(conversationDiagnostics.generatedAt)); return rows.map((row) => copy(row.diagnostic as ConversationDiagnostic)); }
}
