import { and, asc, eq } from 'drizzle-orm';

import type { TenantContext } from '@platform/contracts';
import {
  acquisitionRevenueDiagnostics,
  acquisitionDataQualityAssessments,
  customerIdentities,
  customerIdentityAliases,
  customerIdentityEdges,
  customerIdentityIdentifiers,
  customerLeadEngagementSignals,
  customerLeadCaptureQuarantine,
  customerLeadIdentityLinks,
  customerLeadQualificationAssessments,
  customerLeads,
  customerLeadSources,
  customerConversationParticipants,
  customerConversationThreads,
  customerProviderCapabilities,
  customerFunnelTransitions,
  leadRoutingRecommendations,
  revenueAttributionAssessments,
  revenueEvents,
  revenueOpportunities,
} from '@platform/db';
import type {
  AcquisitionRevenueDiagnostic,
  AcquisitionDataQualityAssessment,
  CRMProviderCapabilities,
  ConversationEngagementSignal,
  CustomerAcquisitionRevenueStore,
  IdentityIdentifier,
  IdentityAlias,
  IdentityEdge,
  LeadIdentityLink,
  LeadCaptureQuarantine,
  LeadQualificationAssessment,
  LeadRecord,
  LeadRoutingRecommendation,
  PersonIdentity,
  RevenueAttributionAssessment,
  RevenueEvent,
  RevenueOpportunity,
  FunnelTransition,
  ConversationParticipant,
  ConversationThread,
} from '@platform/marketing-os-core';

import type { MarketingOSPersistenceDatabase } from './index.js';

function assertTenant(context: TenantContext, tenantId?: string): asserts context is TenantContext & { tenantId: string } {
  if (!context.tenantId || (tenantId && context.tenantId !== tenantId)) throw new Error('TENANT_SCOPE_DENIED');
}

/** PostgreSQL adapter for provider-neutral EPIC09 records. Every query carries tenant scope; RLS is the second boundary. */
export class PersistentCustomerAcquisitionRevenueStore implements CustomerAcquisitionRevenueStore {
  constructor(private readonly db: MarketingOSPersistenceDatabase) {}

  async findLeadByIdempotencyKey(context: TenantContext, idempotencyKey: string): Promise<LeadRecord | undefined> {
    assertTenant(context);
    const [row] = await this.db.select().from(customerLeads).where(and(eq(customerLeads.tenantId, context.tenantId), eq(customerLeads.idempotencyKey, idempotencyKey))).limit(1);
    return row ? copy(row.lead as LeadRecord) : undefined;
  }
  async saveLead(context: TenantContext, lead: LeadRecord, idempotencyKey: string): Promise<LeadRecord> {
    assertTenant(context, lead.tenantId);
    await this.db.insert(customerLeads).values({ id: lead.leadId, tenantId: lead.tenantId, idempotencyKey, source: lead.source, sourceProvider: lead.sourceProvider ?? null, sourceCampaignId: lead.sourceCampaignId ?? null, unifiedCampaignId: lead.unifiedCampaignId ?? null, normalizedEmail: lead.email ?? null, normalizedPhone: lead.phone ?? null, lead, capturedAt: new Date(lead.capturedAt), createdAt: new Date(lead.createdAt), updatedAt: new Date(lead.updatedAt) }).onConflictDoNothing();
    await this.db.insert(customerLeadSources).values({ id: `${lead.leadId}:source`, tenantId: lead.tenantId, leadId: lead.leadId, source: lead.source, sourceProvider: lead.sourceProvider ?? null, sourceCampaignId: lead.sourceCampaignId ?? null, sourceRecord: { externalLeadIds: lead.externalLeadIds, sourceMetadata: lead.sourceMetadata, evidenceRefs: lead.evidenceRefs }, capturedAt: new Date(lead.capturedAt), createdAt: new Date(lead.createdAt), updatedAt: new Date(lead.updatedAt) }).onConflictDoUpdate({ target: customerLeadSources.id, set: { sourceRecord: { externalLeadIds: lead.externalLeadIds, sourceMetadata: lead.sourceMetadata, evidenceRefs: lead.evidenceRefs }, capturedAt: new Date(lead.capturedAt), updatedAt: new Date(lead.updatedAt) } });
    const persisted = await this.findLeadByIdempotencyKey(context, idempotencyKey);
    if (!persisted) throw new Error('LEAD_SAVE_FAILED');
    if (persisted.leadId !== lead.leadId) throw new Error('LEAD_IDEMPOTENCY_MISMATCH');
    return persisted;
  }
  async saveLeadQuarantine(context: TenantContext, quarantine: LeadCaptureQuarantine): Promise<LeadCaptureQuarantine> { assertTenant(context, quarantine.tenantId); await this.db.insert(customerLeadCaptureQuarantine).values({ id: quarantine.quarantineId, tenantId: quarantine.tenantId, idempotencyKey: quarantine.idempotencyKey, code: quarantine.code, reason: quarantine.reason, capturedAt: new Date(quarantine.capturedAt) }).onConflictDoUpdate({ target: [customerLeadCaptureQuarantine.tenantId, customerLeadCaptureQuarantine.idempotencyKey], set: { code: quarantine.code, reason: quarantine.reason, capturedAt: new Date(quarantine.capturedAt) } }); return copy(quarantine); }
  async getLead(context: TenantContext, leadId: string): Promise<LeadRecord | undefined> {
    assertTenant(context);
    const [row] = await this.db.select().from(customerLeads).where(and(eq(customerLeads.tenantId, context.tenantId), eq(customerLeads.id, leadId))).limit(1);
    return row ? copy(row.lead as LeadRecord) : undefined;
  }
  async listLeads(context: TenantContext): Promise<LeadRecord[]> { assertTenant(context); const rows = await this.db.select().from(customerLeads).where(eq(customerLeads.tenantId, context.tenantId)).orderBy(asc(customerLeads.capturedAt)); return rows.map((row) => copy(row.lead as LeadRecord)); }

  async findIdentities(context: TenantContext, identifiers: IdentityIdentifier[]): Promise<PersonIdentity[]> {
    assertTenant(context);
    if (!identifiers.length) return [];
    const rows = await this.db.select().from(customerIdentities).where(eq(customerIdentities.tenantId, context.tenantId));
    return rows.map((row) => row.identity as PersonIdentity).filter((identity) => identity.identifiers.some((item) => identifiers.some((expected) => item.type === expected.type && item.normalizedValue === expected.normalizedValue))).map(copy);
  }
  async getIdentity(context: TenantContext, identityId: string): Promise<PersonIdentity | undefined> { assertTenant(context); const [row] = await this.db.select().from(customerIdentities).where(and(eq(customerIdentities.tenantId, context.tenantId), eq(customerIdentities.id, identityId))).limit(1); return row ? copy(row.identity as PersonIdentity) : undefined; }
  async saveIdentity(context: TenantContext, identity: PersonIdentity): Promise<PersonIdentity> {
    assertTenant(context, identity.tenantId);
    await this.db.insert(customerIdentities).values({ id: identity.identityId, tenantId: identity.tenantId, identityType: identity.type, identity, createdAt: new Date(identity.createdAt), updatedAt: new Date(identity.updatedAt) }).onConflictDoUpdate({ target: customerIdentities.id, set: { identity, identityType: identity.type, updatedAt: new Date(identity.updatedAt) } });
    for (const identifier of identity.identifiers) await this.db.insert(customerIdentityIdentifiers).values({ id: `${identity.identityId}:${identifier.type}:${identifier.normalizedValue}`, tenantId: identity.tenantId, identityId: identity.identityId, identifierType: identifier.type, normalizedValue: identifier.normalizedValue, identifier, createdAt: new Date(identity.createdAt), updatedAt: new Date(identity.updatedAt) }).onConflictDoNothing();
    return copy(identity);
  }
  async saveIdentityEdge(context: TenantContext, edge: IdentityEdge): Promise<IdentityEdge> { assertTenant(context, edge.tenantId); await this.db.insert(customerIdentityEdges).values({ id: edge.edgeId, tenantId: edge.tenantId, fromIdentityId: edge.fromIdentityId, toIdentityId: edge.toIdentityId, resolution: edge.resolution, reason: edge.reason, confidence: edge.confidence, evidenceRefs: edge.evidenceRefs, resolverVersion: edge.resolverVersion, createdAt: new Date(edge.createdAt) }).onConflictDoUpdate({ target: [customerIdentityEdges.tenantId, customerIdentityEdges.fromIdentityId, customerIdentityEdges.toIdentityId], set: { resolution: edge.resolution, reason: edge.reason, confidence: edge.confidence, evidenceRefs: edge.evidenceRefs, resolverVersion: edge.resolverVersion } }); return copy(edge); }
  async listIdentityEdges(context: TenantContext, identityId: string): Promise<IdentityEdge[]> { assertTenant(context); const rows = await this.db.select().from(customerIdentityEdges).where(eq(customerIdentityEdges.tenantId, context.tenantId)).orderBy(asc(customerIdentityEdges.createdAt)); return rows.filter((row) => row.fromIdentityId === identityId || row.toIdentityId === identityId).map((row) => ({ edgeId: row.id, tenantId: row.tenantId, fromIdentityId: row.fromIdentityId, toIdentityId: row.toIdentityId, resolution: row.resolution as IdentityEdge['resolution'], reason: row.reason, confidence: row.confidence, evidenceRefs: copy(row.evidenceRefs as IdentityEdge['evidenceRefs']), resolverVersion: row.resolverVersion, createdAt: row.createdAt.toISOString() })); }
  async saveIdentityAlias(context: TenantContext, alias: IdentityAlias): Promise<IdentityAlias> { assertTenant(context, alias.tenantId); await this.db.insert(customerIdentityAliases).values({ id: alias.aliasId, tenantId: alias.tenantId, identityId: alias.identityId, alias: alias.alias, reason: alias.reason, evidenceRefs: alias.evidenceRefs, createdAt: new Date(alias.createdAt), updatedAt: new Date(alias.updatedAt) }).onConflictDoUpdate({ target: [customerIdentityAliases.tenantId, customerIdentityAliases.identityId, customerIdentityAliases.alias], set: { reason: alias.reason, evidenceRefs: alias.evidenceRefs, updatedAt: new Date(alias.updatedAt) } }); return copy(alias); }
  async listIdentityAliases(context: TenantContext, identityId: string): Promise<IdentityAlias[]> { assertTenant(context); const rows = await this.db.select().from(customerIdentityAliases).where(and(eq(customerIdentityAliases.tenantId, context.tenantId), eq(customerIdentityAliases.identityId, identityId))).orderBy(asc(customerIdentityAliases.createdAt)); return rows.map((row) => ({ aliasId: row.id, tenantId: row.tenantId, identityId: row.identityId, alias: row.alias, reason: row.reason, evidenceRefs: copy(row.evidenceRefs as IdentityAlias['evidenceRefs']), createdAt: row.createdAt.toISOString(), updatedAt: row.updatedAt.toISOString() })); }
  async saveLeadIdentityLink(context: TenantContext, link: LeadIdentityLink): Promise<LeadIdentityLink> { assertTenant(context, link.tenantId); await this.db.insert(customerLeadIdentityLinks).values({ id: link.linkId, tenantId: link.tenantId, leadId: link.leadId, identityId: link.identityId, resolution: link.resolution, reason: link.reason, confidence: link.confidence, evidenceRefs: link.evidenceRefs, resolverVersion: link.resolverVersion, createdAt: new Date(link.createdAt) }).onConflictDoUpdate({ target: [customerLeadIdentityLinks.tenantId, customerLeadIdentityLinks.leadId, customerLeadIdentityLinks.identityId], set: { resolution: link.resolution, reason: link.reason, confidence: link.confidence, evidenceRefs: link.evidenceRefs, resolverVersion: link.resolverVersion } }); return copy(link); }
  async listLeadIdentityLinks(context: TenantContext, leadId: string): Promise<LeadIdentityLink[]> { assertTenant(context); const rows = await this.db.select().from(customerLeadIdentityLinks).where(and(eq(customerLeadIdentityLinks.tenantId, context.tenantId), eq(customerLeadIdentityLinks.leadId, leadId))).orderBy(asc(customerLeadIdentityLinks.createdAt)); return rows.map((row) => ({ linkId: row.id, tenantId: row.tenantId, leadId: row.leadId, identityId: row.identityId, resolution: row.resolution as LeadIdentityLink['resolution'], reason: row.reason, confidence: row.confidence, evidenceRefs: copy(row.evidenceRefs as LeadIdentityLink['evidenceRefs']), resolverVersion: row.resolverVersion, createdAt: row.createdAt.toISOString() })); }

  async saveSignal(context: TenantContext, signal: ConversationEngagementSignal): Promise<ConversationEngagementSignal> { assertTenant(context, signal.tenantId); await this.db.insert(customerLeadEngagementSignals).values({ id: signal.signalId, tenantId: signal.tenantId, leadId: signal.leadId, signalType: signal.type, channel: signal.channel ?? null, source: signal.source, occurredAt: new Date(signal.occurredAt), confidence: signal.confidence, evidenceRefs: signal.evidenceRefs }).onConflictDoUpdate({ target: customerLeadEngagementSignals.id, set: { signalType: signal.type, channel: signal.channel ?? null, source: signal.source, occurredAt: new Date(signal.occurredAt), confidence: signal.confidence, evidenceRefs: signal.evidenceRefs } }); return copy(signal); }
  async listSignals(context: TenantContext, leadId: string): Promise<ConversationEngagementSignal[]> { assertTenant(context); const rows = await this.db.select().from(customerLeadEngagementSignals).where(and(eq(customerLeadEngagementSignals.tenantId, context.tenantId), eq(customerLeadEngagementSignals.leadId, leadId))).orderBy(asc(customerLeadEngagementSignals.occurredAt)); return rows.map((row) => ({ signalId: row.id, tenantId: row.tenantId, leadId: row.leadId, type: row.signalType as ConversationEngagementSignal['type'], ...(row.channel ? { channel: row.channel as NonNullable<ConversationEngagementSignal['channel']> } : {}), source: row.source, occurredAt: row.occurredAt.toISOString(), confidence: row.confidence, evidenceRefs: copy(row.evidenceRefs as ConversationEngagementSignal['evidenceRefs']) })); }
  async saveConversationThread(context: TenantContext, thread: ConversationThread): Promise<ConversationThread> { assertTenant(context, thread.tenantId); await this.db.insert(customerConversationThreads).values({ id: thread.threadId, tenantId: thread.tenantId, channel: thread.channel, externalThreadId: thread.externalThreadId ?? null, thread, startedAt: new Date(thread.startedAt), lastMessageAt: thread.lastMessageAt ? new Date(thread.lastMessageAt) : null }).onConflictDoUpdate({ target: customerConversationThreads.id, set: { thread, channel: thread.channel, externalThreadId: thread.externalThreadId ?? null, lastMessageAt: thread.lastMessageAt ? new Date(thread.lastMessageAt) : null } }); return copy(thread); }
  async listConversationThreads(context: TenantContext): Promise<ConversationThread[]> { assertTenant(context); const rows = await this.db.select().from(customerConversationThreads).where(eq(customerConversationThreads.tenantId, context.tenantId)).orderBy(asc(customerConversationThreads.startedAt)); return rows.map((row) => copy(row.thread as ConversationThread)); }
  async saveConversationParticipant(context: TenantContext, participant: ConversationParticipant): Promise<ConversationParticipant> { assertTenant(context, participant.tenantId); await this.db.insert(customerConversationParticipants).values({ id: participant.participantId, tenantId: participant.tenantId, threadId: participant.threadId, identityId: participant.identityId ?? null, externalParticipantId: participant.externalParticipantId ?? null, participant }).onConflictDoUpdate({ target: customerConversationParticipants.id, set: { identityId: participant.identityId ?? null, externalParticipantId: participant.externalParticipantId ?? null, participant } }); return copy(participant); }
  async listConversationParticipants(context: TenantContext, threadId: string): Promise<ConversationParticipant[]> { assertTenant(context); const rows = await this.db.select().from(customerConversationParticipants).where(and(eq(customerConversationParticipants.tenantId, context.tenantId), eq(customerConversationParticipants.threadId, threadId))).orderBy(asc(customerConversationParticipants.createdAt)); return rows.map((row) => copy(row.participant as ConversationParticipant)); }
  async saveQualification(context: TenantContext, assessment: LeadQualificationAssessment): Promise<LeadQualificationAssessment> { assertTenant(context, assessment.tenantId); await this.db.insert(customerLeadQualificationAssessments).values({ id: assessment.assessmentId, tenantId: assessment.tenantId, leadId: assessment.leadId, assessment, ruleVersion: assessment.ruleVersion, assessedAt: new Date(assessment.assessedAt) }).onConflictDoUpdate({ target: [customerLeadQualificationAssessments.tenantId, customerLeadQualificationAssessments.leadId], set: { id: assessment.assessmentId, assessment, ruleVersion: assessment.ruleVersion, assessedAt: new Date(assessment.assessedAt) } }); return copy(assessment); }
  async getQualification(context: TenantContext, leadId: string): Promise<LeadQualificationAssessment | undefined> { assertTenant(context); const [row] = await this.db.select().from(customerLeadQualificationAssessments).where(and(eq(customerLeadQualificationAssessments.tenantId, context.tenantId), eq(customerLeadQualificationAssessments.leadId, leadId))).limit(1); return row ? copy(row.assessment as LeadQualificationAssessment) : undefined; }

  async saveOpportunity(context: TenantContext, opportunity: RevenueOpportunity): Promise<RevenueOpportunity> { assertTenant(context, opportunity.tenantId); await this.db.insert(revenueOpportunities).values({ id: opportunity.opportunityId, tenantId: opportunity.tenantId, externalOpportunityId: opportunity.externalOpportunityId ?? null, provider: opportunity.provider, stage: opportunity.stage, status: opportunity.status, amountMinor: opportunity.amountMinor ?? null, currency: opportunity.currency ?? null, opportunity, closedAt: opportunity.closedAt ? new Date(opportunity.closedAt) : null, createdAt: new Date(opportunity.createdAt), updatedAt: new Date(opportunity.updatedAt) }).onConflictDoUpdate({ target: revenueOpportunities.id, set: { externalOpportunityId: opportunity.externalOpportunityId ?? null, stage: opportunity.stage, status: opportunity.status, amountMinor: opportunity.amountMinor ?? null, currency: opportunity.currency ?? null, opportunity, closedAt: opportunity.closedAt ? new Date(opportunity.closedAt) : null, updatedAt: new Date(opportunity.updatedAt) } }); return copy(opportunity); }
  async getOpportunity(context: TenantContext, opportunityId: string): Promise<RevenueOpportunity | undefined> { assertTenant(context); const [row] = await this.db.select().from(revenueOpportunities).where(and(eq(revenueOpportunities.tenantId, context.tenantId), eq(revenueOpportunities.id, opportunityId))).limit(1); return row ? copy(row.opportunity as RevenueOpportunity) : undefined; }
  async listOpportunities(context: TenantContext): Promise<RevenueOpportunity[]> { assertTenant(context); const rows = await this.db.select().from(revenueOpportunities).where(eq(revenueOpportunities.tenantId, context.tenantId)).orderBy(asc(revenueOpportunities.createdAt)); return rows.map((row) => copy(row.opportunity as RevenueOpportunity)); }
  async saveRevenueEvent(context: TenantContext, event: RevenueEvent): Promise<RevenueEvent> { assertTenant(context, event.tenantId); await this.db.insert(revenueEvents).values({ id: event.eventId, tenantId: event.tenantId, opportunityId: event.opportunityId ?? null, eventType: event.type, amountMinor: event.amountMinor ?? null, currency: event.currency ?? null, externalEventId: event.externalEventId ?? null, idempotencyKey: event.idempotencyKey, verificationState: event.verificationState, event, occurredAt: new Date(event.occurredAt) }).onConflictDoNothing(); const [row] = await this.db.select().from(revenueEvents).where(and(eq(revenueEvents.tenantId, context.tenantId), eq(revenueEvents.idempotencyKey, event.idempotencyKey))).limit(1); if (!row) throw new Error('REVENUE_EVENT_SAVE_FAILED'); const persisted = row.event as RevenueEvent; if (persisted.eventId !== event.eventId) throw new Error('REVENUE_EVENT_IDEMPOTENCY_MISMATCH'); return copy(persisted); }
  async listRevenueEvents(context: TenantContext): Promise<RevenueEvent[]> { assertTenant(context); const rows = await this.db.select().from(revenueEvents).where(eq(revenueEvents.tenantId, context.tenantId)).orderBy(asc(revenueEvents.occurredAt)); return rows.map((row) => copy(row.event as RevenueEvent)); }
  async saveAttribution(context: TenantContext, assessment: RevenueAttributionAssessment): Promise<RevenueAttributionAssessment> { assertTenant(context, assessment.tenantId); await this.db.insert(revenueAttributionAssessments).values({ id: assessment.assessmentId, tenantId: assessment.tenantId, revenueEventId: assessment.revenueEventId, opportunityId: assessment.opportunityId ?? null, model: assessment.model, confidence: assessment.confidence, assessment, assessedAt: new Date(assessment.assessedAt) }).onConflictDoUpdate({ target: [revenueAttributionAssessments.tenantId, revenueAttributionAssessments.revenueEventId, revenueAttributionAssessments.model], set: { assessment, confidence: assessment.confidence, assessedAt: new Date(assessment.assessedAt) } }); return copy(assessment); }
  async listAttribution(context: TenantContext): Promise<RevenueAttributionAssessment[]> { assertTenant(context); const rows = await this.db.select().from(revenueAttributionAssessments).where(eq(revenueAttributionAssessments.tenantId, context.tenantId)).orderBy(asc(revenueAttributionAssessments.assessedAt)); return rows.map((row) => copy(row.assessment as RevenueAttributionAssessment)); }
  async saveFunnelTransition(context: TenantContext, transition: FunnelTransition): Promise<FunnelTransition> { assertTenant(context, transition.tenantId); await this.db.insert(customerFunnelTransitions).values({ id: transition.transitionId, tenantId: transition.tenantId, leadId: transition.leadId ?? null, opportunityId: transition.opportunityId ?? null, fromStage: transition.fromStage ?? null, toStage: transition.toStage, sourceCampaignId: transition.sourceCampaignId ?? null, transition, occurredAt: new Date(transition.occurredAt) }).onConflictDoUpdate({ target: customerFunnelTransitions.id, set: { transition, occurredAt: new Date(transition.occurredAt) } }); return copy(transition); }
  async listFunnelTransitions(context: TenantContext): Promise<FunnelTransition[]> { assertTenant(context); const rows = await this.db.select().from(customerFunnelTransitions).where(eq(customerFunnelTransitions.tenantId, context.tenantId)).orderBy(asc(customerFunnelTransitions.occurredAt)); return rows.map((row) => copy(row.transition as FunnelTransition)); }
  async saveDiagnostic(context: TenantContext, diagnostic: AcquisitionRevenueDiagnostic): Promise<AcquisitionRevenueDiagnostic> { assertTenant(context, diagnostic.tenantId); await this.db.insert(acquisitionRevenueDiagnostics).values({ id: diagnostic.diagnosticId, tenantId: diagnostic.tenantId, diagnosticType: diagnostic.type, severity: diagnostic.severity, diagnostic, generatedAt: new Date(diagnostic.generatedAt) }).onConflictDoUpdate({ target: acquisitionRevenueDiagnostics.id, set: { diagnosticType: diagnostic.type, severity: diagnostic.severity, diagnostic, generatedAt: new Date(diagnostic.generatedAt) } }); return copy(diagnostic); }
  async listDiagnostics(context: TenantContext): Promise<AcquisitionRevenueDiagnostic[]> { assertTenant(context); const rows = await this.db.select().from(acquisitionRevenueDiagnostics).where(eq(acquisitionRevenueDiagnostics.tenantId, context.tenantId)).orderBy(asc(acquisitionRevenueDiagnostics.generatedAt)); return rows.map((row) => copy(row.diagnostic as AcquisitionRevenueDiagnostic)); }
  async saveRoutingRecommendation(context: TenantContext, recommendation: LeadRoutingRecommendation): Promise<LeadRoutingRecommendation> { assertTenant(context, recommendation.tenantId); await this.db.insert(leadRoutingRecommendations).values({ id: recommendation.recommendationId, tenantId: recommendation.tenantId, leadId: recommendation.leadId, kind: recommendation.kind, recommendation, createdAt: new Date(recommendation.createdAt) }).onConflictDoUpdate({ target: [leadRoutingRecommendations.tenantId, leadRoutingRecommendations.leadId, leadRoutingRecommendations.kind], set: { recommendation, createdAt: new Date(recommendation.createdAt) } }); return copy(recommendation); }
  async listRoutingRecommendations(context: TenantContext): Promise<LeadRoutingRecommendation[]> { assertTenant(context); const rows = await this.db.select().from(leadRoutingRecommendations).where(eq(leadRoutingRecommendations.tenantId, context.tenantId)).orderBy(asc(leadRoutingRecommendations.createdAt)); return rows.map((row) => copy(row.recommendation as LeadRoutingRecommendation)); }
  async saveDataQualityAssessment(context: TenantContext, assessment: AcquisitionDataQualityAssessment): Promise<AcquisitionDataQualityAssessment> { assertTenant(context, assessment.tenantId); await this.db.insert(acquisitionDataQualityAssessments).values({ id: assessment.assessmentId, tenantId: assessment.tenantId, subjectType: assessment.subjectType, subjectId: assessment.subjectId, assessment, assessedAt: new Date(assessment.assessedAt) }).onConflictDoUpdate({ target: acquisitionDataQualityAssessments.id, set: { assessment, assessedAt: new Date(assessment.assessedAt) } }); return copy(assessment); }
  async listDataQualityAssessments(context: TenantContext): Promise<AcquisitionDataQualityAssessment[]> { assertTenant(context); const rows = await this.db.select().from(acquisitionDataQualityAssessments).where(eq(acquisitionDataQualityAssessments.tenantId, context.tenantId)).orderBy(asc(acquisitionDataQualityAssessments.assessedAt)); return rows.map((row) => copy(row.assessment as AcquisitionDataQualityAssessment)); }
  async saveProviderCapabilities(context: TenantContext, capabilities: CRMProviderCapabilities): Promise<CRMProviderCapabilities> { assertTenant(context, capabilities.tenantId); await this.db.insert(customerProviderCapabilities).values({ id: `${capabilities.tenantId}:${capabilities.provider}`, tenantId: capabilities.tenantId, provider: capabilities.provider, enabled: capabilities.enabled, healthStatus: capabilities.healthStatus, capabilities }).onConflictDoUpdate({ target: [customerProviderCapabilities.tenantId, customerProviderCapabilities.provider], set: { enabled: capabilities.enabled, healthStatus: capabilities.healthStatus, capabilities } }); return copy(capabilities); }
  async listProviderCapabilities(context: TenantContext): Promise<CRMProviderCapabilities[]> { assertTenant(context); const rows = await this.db.select().from(customerProviderCapabilities).where(eq(customerProviderCapabilities.tenantId, context.tenantId)).orderBy(asc(customerProviderCapabilities.provider)); return rows.map((row) => copy(row.capabilities as CRMProviderCapabilities)); }
}

function copy<T>(value: T): T { return structuredClone(value); }
