import { and, asc, eq } from 'drizzle-orm';
import { lifecycleActivationAssessments, lifecycleActivationCandidates, lifecycleActivationLearningLinks, lifecycleActivationOutcomes, lifecycleActivationPlans, lifecycleActivationSteps, lifecycleActivationVerifications } from '@platform/db';
import type { TenantContext } from '@platform/contracts';
import type { ActivationCandidate, ActivationLearningLink, ActivationOutcome, ActivationVerification, LifecycleActivationPlan } from '@platform/marketing-os-core';
import type { MarketingOSPersistenceDatabase } from './index.js';
import { PersistentCustomerJourneyStore } from './customer-journey-lifecycle.js';
import type { JourneyActionOutcome, JourneyLearningRecord } from '@platform/marketing-os-core';
const copy = <T>(value: T): T => structuredClone(value);
function tenant(context: TenantContext, id?: string): asserts context is TenantContext & { tenantId: string } { if (!context.tenantId || (id && id !== context.tenantId)) throw new Error('TENANT_SCOPE_DENIED'); }
/** Durable EPIC12 recommendation/governance evidence. It has no provider transport surface. */
export class PersistentLifecycleActivationStore {
  constructor(private readonly db: MarketingOSPersistenceDatabase) {}
  async savePlan(context: TenantContext, plan: LifecycleActivationPlan): Promise<LifecycleActivationPlan> { tenant(context, plan.tenantId); await this.db.insert(lifecycleActivationPlans).values({ id: plan.planId, tenantId: plan.tenantId, identityId: plan.identityId, nextBestActionId: plan.nextBestActionId, status: plan.state, idempotencyKey: plan.idempotencyKey, plan, createdAt: new Date(), updatedAt: new Date() }).onConflictDoNothing(); for (const step of plan.steps) await this.db.insert(lifecycleActivationSteps).values({ id: step.stepId, tenantId: plan.tenantId, planId: plan.planId, sequence: step.sequence, status: step.state, step, createdAt: new Date(), updatedAt: new Date() }).onConflictDoNothing(); const saved = await this.getPlan(context, plan.idempotencyKey); if (!saved) throw new Error('ACTIVATION_PLAN_SAVE_FAILED'); return saved; }
  async getPlan(context: TenantContext, key: string): Promise<LifecycleActivationPlan | undefined> { tenant(context); const [row] = await this.db.select().from(lifecycleActivationPlans).where(and(eq(lifecycleActivationPlans.tenantId, context.tenantId), eq(lifecycleActivationPlans.idempotencyKey, key))).limit(1); return row ? copy(row.plan as LifecycleActivationPlan) : undefined; }
  async saveCandidate(context: TenantContext, planId: string, candidate: ActivationCandidate): Promise<ActivationCandidate> { tenant(context, candidate.tenantId); await this.db.insert(lifecycleActivationCandidates).values({ id: candidate.candidateId, tenantId: candidate.tenantId, planId, identityId: candidate.identityId, channel: candidate.channel, status: candidate.state, idempotencyKey: candidate.idempotencyKey, candidate, createdAt: new Date(), updatedAt: new Date() }).onConflictDoNothing(); const saved = await this.getCandidate(context, candidate.idempotencyKey); if (!saved) throw new Error('ACTIVATION_CANDIDATE_SAVE_FAILED'); return saved; }
  async getCandidate(context: TenantContext, key: string): Promise<ActivationCandidate | undefined> { tenant(context); const [row] = await this.db.select().from(lifecycleActivationCandidates).where(and(eq(lifecycleActivationCandidates.tenantId, context.tenantId), eq(lifecycleActivationCandidates.idempotencyKey, key))).limit(1); return row ? copy(row.candidate as ActivationCandidate) : undefined; }
  async addAssessment(context: TenantContext, candidateId: string, type: string, assessment: unknown): Promise<void> { tenant(context); await this.db.insert(lifecycleActivationAssessments).values({ id: `${candidateId}:${type}`, tenantId: context.tenantId, candidateId, assessmentType: type, assessment, assessedAt: new Date(), createdAt: new Date(), updatedAt: new Date() }).onConflictDoNothing(); }
  async listAssessments(context: TenantContext, candidateId: string): Promise<unknown[]> { tenant(context); const rows = await this.db.select().from(lifecycleActivationAssessments).where(and(eq(lifecycleActivationAssessments.tenantId, context.tenantId), eq(lifecycleActivationAssessments.candidateId, candidateId))).orderBy(asc(lifecycleActivationAssessments.assessedAt)); return rows.map((row) => copy(row.assessment)); }
  async saveOutcome(context: TenantContext, input: { outcomeId: string; identityId: string; executionId?: string; idempotencyKey: string; outcome: ActivationOutcome; record: unknown; observedAt: string }): Promise<void> { tenant(context); await this.db.insert(lifecycleActivationOutcomes).values({ id: input.outcomeId, tenantId: context.tenantId, identityId: input.identityId, ...(input.executionId ? { executionId: input.executionId } : {}), outcome: input.outcome, idempotencyKey: input.idempotencyKey, outcomeRecord: input.record, observedAt: new Date(input.observedAt), createdAt: new Date(), updatedAt: new Date() }).onConflictDoNothing(); }
  async linkLearning(context: TenantContext, link: ActivationLearningLink): Promise<void> { tenant(context); await this.db.insert(lifecycleActivationLearningLinks).values({ id: `learning:${link.outcomeId}`, tenantId: context.tenantId, activationOutcomeId: link.outcomeId, ...(link.journeyOutcomeId ? { journeyOutcomeId: link.journeyOutcomeId } : {}), ...(link.journeyLearningId ? { journeyLearningId: link.journeyLearningId } : {}), link, createdAt: new Date(), updatedAt: new Date() }).onConflictDoNothing(); }
  async recordVerification(context: TenantContext, verification: ActivationVerification): Promise<void> { tenant(context); await this.db.insert(lifecycleActivationVerifications).values({ id: verification.verificationId, tenantId: context.tenantId, executionId: verification.executionId, status: verification.state, verification, verifiedAt: new Date(), createdAt: new Date(), updatedAt: new Date() }).onConflictDoNothing(); }
  /** Only independently VERIFIED activation evidence may become EPIC11 outcome/learning records. */
  async materializeVerifiedJourneyLearning(context: TenantContext, verification: ActivationVerification, outcome: JourneyActionOutcome, learning: JourneyLearningRecord): Promise<void> { tenant(context, outcome.tenantId); tenant(context, learning.tenantId); if (verification.state !== 'VERIFIED') throw new Error('ACTIVATION_VERIFICATION_REQUIRED'); const journey = new PersistentCustomerJourneyStore(this.db); await journey.saveOutcome(context, outcome); await journey.saveLearning(context, learning); await this.linkLearning(context, { outcomeId: outcome.outcomeId, journeyOutcomeId: outcome.outcomeId, journeyLearningId: learning.learningId, causalClaim: 'NONE' }); }
}
