import { and, asc, eq } from 'drizzle-orm';
import { externalProviderCredentialHealth, externalProviderHealth, providerIntegrationVerifications, tenantProviderBindings, tenantProviderCapabilities } from '@platform/db';
import type { TenantContext } from '@platform/contracts';
import type { MarketingOSPersistenceDatabase } from './index.js';

const copy=<T>(value:T):T=>structuredClone(value);
function tenant(context:TenantContext):asserts context is TenantContext&{tenantId:string}{if(!context.tenantId)throw new Error('TENANT_SCOPE_DENIED');}
function safeEvidence(value:unknown):Record<string,unknown>{if(!value||typeof value!=='object'||Array.isArray(value))return {};const record=value as Record<string,unknown>;const out:Record<string,unknown>={};for(const [key,item] of Object.entries(record)){if(/token|secret|password|authorization|cookie/i.test(key))continue;if(typeof item==='string'&&item.length>512)out[key]=item.slice(0,512);else if(item===null||typeof item==='string'||typeof item==='number'||typeof item==='boolean')out[key]=item;}return out;}
/** Durable EPIC14 binding metadata. Secret material, health authority, and retries remain outside this adapter. */
export class PersistentProviderIntegrationStore {
  constructor(private readonly db:MarketingOSPersistenceDatabase){}
  async upsertBinding(context:TenantContext,input:{id:string;provider:string;environment:string;executionMode:string;configured:boolean;enabled:boolean;credentialReference?:string;idempotencyKey:string;adapterVersion:string}){tenant(context);const now=new Date();await this.db.insert(tenantProviderBindings).values({id:input.id,tenantId:context.tenantId,provider:input.provider,environment:input.environment,executionMode:input.executionMode,configured:input.configured,enabled:input.enabled,credentialReference:input.credentialReference??null,idempotencyKey:input.idempotencyKey,adapterVersion:input.adapterVersion,createdAt:now,updatedAt:now}).onConflictDoUpdate({target:[tenantProviderBindings.tenantId,tenantProviderBindings.provider,tenantProviderBindings.environment],set:{executionMode:input.executionMode,configured:input.configured,enabled:input.enabled,credentialReference:input.credentialReference??null,idempotencyKey:input.idempotencyKey,adapterVersion:input.adapterVersion,updatedAt:now}});return this.listBindings(context);}
  async listBindings(context:TenantContext){tenant(context);return this.db.select().from(tenantProviderBindings).where(eq(tenantProviderBindings.tenantId,context.tenantId)).orderBy(asc(tenantProviderBindings.provider));}
  async upsertCapability(context:TenantContext,input:{id:string;bindingId:string;capability:string;operation:string;supported:boolean;enabled:boolean;idempotencyKey:string}){tenant(context);const binding=await this.binding(context,input.bindingId);if(!binding)throw new Error('PROVIDER_BINDING_NOT_FOUND_OR_ACCESS_DENIED');const now=new Date();await this.db.insert(tenantProviderCapabilities).values({id:input.id,tenantId:context.tenantId,bindingId:input.bindingId,capability:input.capability,operation:input.operation,supported:input.supported,enabled:input.enabled,idempotencyKey:input.idempotencyKey,createdAt:now,updatedAt:now}).onConflictDoUpdate({target:[tenantProviderCapabilities.tenantId,tenantProviderCapabilities.bindingId,tenantProviderCapabilities.capability],set:{operation:input.operation,supported:input.supported,enabled:input.enabled,idempotencyKey:input.idempotencyKey,updatedAt:now}});return this.listCapabilities(context);}
  async listCapabilities(context:TenantContext){tenant(context);return this.db.select().from(tenantProviderCapabilities).where(eq(tenantProviderCapabilities.tenantId,context.tenantId)).orderBy(asc(tenantProviderCapabilities.capability));}
  async recordVerification(context:TenantContext,input:{id:string;bindingId:string;capability:string;state:string;providerReference?:string;evidence:unknown;idempotencyKey:string;verified?:boolean}){tenant(context);const binding=await this.binding(context,input.bindingId);if(!binding)throw new Error('PROVIDER_BINDING_NOT_FOUND_OR_ACCESS_DENIED');const now=new Date();await this.db.insert(providerIntegrationVerifications).values({id:input.id,tenantId:context.tenantId,bindingId:input.bindingId,capability:input.capability,state:input.state,providerReference:input.providerReference??null,evidence:safeEvidence(input.evidence),idempotencyKey:input.idempotencyKey,verifiedAt:input.verified?now:null,createdAt:now,updatedAt:now}).onConflictDoNothing();}
  async listVerifications(context:TenantContext,bindingId?:string){tenant(context);const where=bindingId?and(eq(providerIntegrationVerifications.tenantId,context.tenantId),eq(providerIntegrationVerifications.bindingId,bindingId)):eq(providerIntegrationVerifications.tenantId,context.tenantId);const values=await this.db.select().from(providerIntegrationVerifications).where(where).orderBy(asc(providerIntegrationVerifications.createdAt));return values.map(copy);}
  async health(context:TenantContext,provider:string){tenant(context);const [providerHealth,credentialHealth]=await Promise.all([this.db.select().from(externalProviderHealth).where(and(eq(externalProviderHealth.tenantId,context.tenantId),eq(externalProviderHealth.provider,provider))).limit(1),this.db.select().from(externalProviderCredentialHealth).where(and(eq(externalProviderCredentialHealth.tenantId,context.tenantId),eq(externalProviderCredentialHealth.provider,provider))).limit(1)]);return {providerHealth:providerHealth[0]?.status??'UNKNOWN',credentialHealth:credentialHealth[0]?.status??'UNKNOWN'};}
  private async binding(context:TenantContext,id:string){const [row]=await this.db.select().from(tenantProviderBindings).where(and(eq(tenantProviderBindings.tenantId,context.tenantId),eq(tenantProviderBindings.id,id))).limit(1);return row;}
}
