-- EPIC-09: provider-neutral customer acquisition, identity, and revenue intelligence.
-- No CRM credential, provider DTO, or message body is stored in this schema.
BEGIN;

CREATE TABLE IF NOT EXISTS customer_identities (id varchar(255) PRIMARY KEY, tenant_id uuid NOT NULL REFERENCES tenants(id), identity_type varchar(32) NOT NULL, identity jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), CONSTRAINT customer_identities_tenant_id_uidx UNIQUE (tenant_id, id));
CREATE TABLE IF NOT EXISTS customer_identity_identifiers (id varchar(255) PRIMARY KEY, tenant_id uuid NOT NULL REFERENCES tenants(id), identity_id varchar(255) NOT NULL REFERENCES customer_identities(id) ON DELETE CASCADE, identifier_type varchar(64) NOT NULL, normalized_value text NOT NULL, identifier jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), CONSTRAINT customer_identity_identifier_tenant_value_uidx UNIQUE (tenant_id, identifier_type, normalized_value));
CREATE INDEX IF NOT EXISTS customer_identity_identifier_tenant_identity_idx ON customer_identity_identifiers (tenant_id, identity_id);
CREATE TABLE IF NOT EXISTS customer_identity_edges (id varchar(255) PRIMARY KEY, tenant_id uuid NOT NULL REFERENCES tenants(id), from_identity_id varchar(255) NOT NULL REFERENCES customer_identities(id) ON DELETE CASCADE, to_identity_id varchar(255) NOT NULL REFERENCES customer_identities(id) ON DELETE CASCADE, resolution varchar(32) NOT NULL, reason text NOT NULL, confidence real NOT NULL, evidence_refs jsonb NOT NULL, resolver_version varchar(64) NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), CONSTRAINT customer_identity_edges_tenant_pair_uidx UNIQUE (tenant_id, from_identity_id, to_identity_id));
CREATE TABLE IF NOT EXISTS customer_identity_aliases (id varchar(255) PRIMARY KEY, tenant_id uuid NOT NULL REFERENCES tenants(id), identity_id varchar(255) NOT NULL REFERENCES customer_identities(id) ON DELETE CASCADE, alias text NOT NULL, reason text NOT NULL, evidence_refs jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), CONSTRAINT customer_identity_aliases_tenant_identity_alias_uidx UNIQUE (tenant_id, identity_id, alias));
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS customer_leads (id varchar(255) PRIMARY KEY, tenant_id uuid NOT NULL REFERENCES tenants(id), idempotency_key varchar(255) NOT NULL, source varchar(96) NOT NULL, source_provider varchar(96), source_campaign_id varchar(255), unified_campaign_id varchar(255), normalized_email text, normalized_phone text, lead jsonb NOT NULL, captured_at timestamptz NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), CONSTRAINT customer_leads_tenant_idempotency_uidx UNIQUE (tenant_id, idempotency_key));
CREATE INDEX IF NOT EXISTS customer_leads_tenant_campaign_idx ON customer_leads (tenant_id, unified_campaign_id);
CREATE INDEX IF NOT EXISTS customer_leads_tenant_email_idx ON customer_leads (tenant_id, normalized_email);
CREATE INDEX IF NOT EXISTS customer_leads_tenant_phone_idx ON customer_leads (tenant_id, normalized_phone);
CREATE TABLE IF NOT EXISTS customer_lead_capture_quarantine (id varchar(255) PRIMARY KEY, tenant_id uuid NOT NULL REFERENCES tenants(id), idempotency_key varchar(255) NOT NULL, code varchar(64) NOT NULL, reason varchar(128) NOT NULL, captured_at timestamptz NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), CONSTRAINT customer_lead_quarantine_tenant_idempotency_uidx UNIQUE (tenant_id, idempotency_key));
CREATE TABLE IF NOT EXISTS customer_lead_sources (id varchar(255) PRIMARY KEY, tenant_id uuid NOT NULL REFERENCES tenants(id), lead_id varchar(255) NOT NULL REFERENCES customer_leads(id) ON DELETE CASCADE, source varchar(96) NOT NULL, source_provider varchar(96), source_campaign_id varchar(255), source_record jsonb NOT NULL, captured_at timestamptz NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS customer_lead_identity_links (id varchar(255) PRIMARY KEY, tenant_id uuid NOT NULL REFERENCES tenants(id), lead_id varchar(255) NOT NULL REFERENCES customer_leads(id) ON DELETE CASCADE, identity_id varchar(255) NOT NULL REFERENCES customer_identities(id) ON DELETE CASCADE, resolution varchar(32) NOT NULL, reason text NOT NULL, confidence real NOT NULL, evidence_refs jsonb NOT NULL, resolver_version varchar(64) NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), CONSTRAINT customer_lead_identity_link_tenant_pair_uidx UNIQUE (tenant_id, lead_id, identity_id));
CREATE TABLE IF NOT EXISTS customer_lead_engagement_signals (id varchar(255) PRIMARY KEY, tenant_id uuid NOT NULL REFERENCES tenants(id), lead_id varchar(255) NOT NULL REFERENCES customer_leads(id) ON DELETE CASCADE, signal_type varchar(64) NOT NULL, channel varchar(32), source varchar(96) NOT NULL, occurred_at timestamptz NOT NULL, confidence real NOT NULL, evidence_refs jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS customer_lead_engagement_tenant_lead_occurred_idx ON customer_lead_engagement_signals (tenant_id, lead_id, occurred_at);
CREATE TABLE IF NOT EXISTS customer_lead_qualification_assessments (id varchar(255) PRIMARY KEY, tenant_id uuid NOT NULL REFERENCES tenants(id), lead_id varchar(255) NOT NULL REFERENCES customer_leads(id) ON DELETE CASCADE, assessment jsonb NOT NULL, rule_version varchar(64) NOT NULL, assessed_at timestamptz NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), CONSTRAINT customer_lead_qualification_tenant_lead_uidx UNIQUE (tenant_id, lead_id));
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS customer_conversation_threads (id varchar(255) PRIMARY KEY, tenant_id uuid NOT NULL REFERENCES tenants(id), channel varchar(32) NOT NULL, external_thread_id varchar(255), thread jsonb NOT NULL, started_at timestamptz NOT NULL, last_message_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), CONSTRAINT customer_conversation_thread_tenant_external_uidx UNIQUE (tenant_id, channel, external_thread_id));
CREATE TABLE IF NOT EXISTS customer_conversation_participants (id varchar(255) PRIMARY KEY, tenant_id uuid NOT NULL REFERENCES tenants(id), thread_id varchar(255) NOT NULL REFERENCES customer_conversation_threads(id) ON DELETE CASCADE, identity_id varchar(255) REFERENCES customer_identities(id) ON DELETE SET NULL, external_participant_id varchar(255), participant jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS customer_conversation_participant_tenant_thread_idx ON customer_conversation_participants (tenant_id, thread_id);
CREATE TABLE IF NOT EXISTS revenue_opportunities (id varchar(255) PRIMARY KEY, tenant_id uuid NOT NULL REFERENCES tenants(id), external_opportunity_id varchar(255), provider varchar(64) NOT NULL, stage varchar(32) NOT NULL, status varchar(32) NOT NULL, amount_minor bigint, currency varchar(3), opportunity jsonb NOT NULL, closed_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), CONSTRAINT revenue_opportunity_tenant_provider_external_uidx UNIQUE (tenant_id, provider, external_opportunity_id));
CREATE INDEX IF NOT EXISTS revenue_opportunity_tenant_stage_idx ON revenue_opportunities (tenant_id, stage);
CREATE TABLE IF NOT EXISTS revenue_events (id varchar(255) PRIMARY KEY, tenant_id uuid NOT NULL REFERENCES tenants(id), opportunity_id varchar(255) REFERENCES revenue_opportunities(id) ON DELETE SET NULL, event_type varchar(48) NOT NULL, amount_minor bigint, currency varchar(3), external_event_id varchar(255), idempotency_key varchar(255) NOT NULL, verification_state varchar(16) NOT NULL, event jsonb NOT NULL, occurred_at timestamptz NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), CONSTRAINT revenue_event_tenant_idempotency_uidx UNIQUE (tenant_id, idempotency_key));
CREATE INDEX IF NOT EXISTS revenue_event_tenant_opportunity_idx ON revenue_events (tenant_id, opportunity_id);
CREATE TABLE IF NOT EXISTS revenue_attribution_assessments (id varchar(255) PRIMARY KEY, tenant_id uuid NOT NULL REFERENCES tenants(id), revenue_event_id varchar(255) NOT NULL REFERENCES revenue_events(id) ON DELETE CASCADE, opportunity_id varchar(255) REFERENCES revenue_opportunities(id) ON DELETE SET NULL, model varchar(48) NOT NULL, confidence real NOT NULL, assessment jsonb NOT NULL, assessed_at timestamptz NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), CONSTRAINT revenue_attribution_tenant_event_model_uidx UNIQUE (tenant_id, revenue_event_id, model));
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS customer_funnel_transitions (id varchar(255) PRIMARY KEY, tenant_id uuid NOT NULL REFERENCES tenants(id), lead_id varchar(255) REFERENCES customer_leads(id) ON DELETE SET NULL, opportunity_id varchar(255) REFERENCES revenue_opportunities(id) ON DELETE SET NULL, from_stage varchar(32), to_stage varchar(32) NOT NULL, source_campaign_id varchar(255), transition jsonb NOT NULL, occurred_at timestamptz NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS customer_funnel_transition_tenant_stage_idx ON customer_funnel_transitions (tenant_id, to_stage, occurred_at);
CREATE TABLE IF NOT EXISTS acquisition_revenue_diagnostics (id varchar(255) PRIMARY KEY, tenant_id uuid NOT NULL REFERENCES tenants(id), diagnostic_type varchar(64) NOT NULL, severity varchar(16) NOT NULL, diagnostic jsonb NOT NULL, generated_at timestamptz NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS acquisition_revenue_diagnostic_tenant_generated_idx ON acquisition_revenue_diagnostics (tenant_id, generated_at);
CREATE TABLE IF NOT EXISTS lead_routing_recommendations (id varchar(255) PRIMARY KEY, tenant_id uuid NOT NULL REFERENCES tenants(id), lead_id varchar(255) NOT NULL REFERENCES customer_leads(id) ON DELETE CASCADE, kind varchar(64) NOT NULL, recommendation jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), CONSTRAINT lead_routing_recommendation_tenant_lead_kind_uidx UNIQUE (tenant_id, lead_id, kind));
CREATE TABLE IF NOT EXISTS acquisition_data_quality_assessments (id varchar(255) PRIMARY KEY, tenant_id uuid NOT NULL REFERENCES tenants(id), subject_type varchar(32) NOT NULL, subject_id varchar(255) NOT NULL, assessment jsonb NOT NULL, assessed_at timestamptz NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS acquisition_data_quality_tenant_subject_idx ON acquisition_data_quality_assessments (tenant_id, subject_type, subject_id);
CREATE TABLE IF NOT EXISTS customer_provider_capabilities (id varchar(255) PRIMARY KEY, tenant_id uuid NOT NULL REFERENCES tenants(id), provider varchar(64) NOT NULL, enabled boolean NOT NULL, health_status varchar(16) NOT NULL, capabilities jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), CONSTRAINT customer_provider_capability_tenant_provider_uidx UNIQUE (tenant_id, provider));
--> statement-breakpoint
DO $$ DECLARE item text; BEGIN
  FOREACH item IN ARRAY ARRAY['customer_identities','customer_identity_identifiers','customer_identity_edges','customer_identity_aliases','customer_leads','customer_lead_capture_quarantine','customer_lead_sources','customer_lead_identity_links','customer_lead_engagement_signals','customer_lead_qualification_assessments','customer_conversation_threads','customer_conversation_participants','revenue_opportunities','revenue_events','revenue_attribution_assessments','customer_funnel_transitions','acquisition_revenue_diagnostics','lead_routing_recommendations','acquisition_data_quality_assessments','customer_provider_capabilities'] LOOP
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', item);
    EXECUTE format('DROP POLICY IF EXISTS %I ON %I', item || '_tenant_policy', item);
    EXECUTE format('CREATE POLICY %I ON %I USING (tenant_id = NULLIF(current_setting(''app.tenant_id'', true), '''')::uuid) WITH CHECK (tenant_id = NULLIF(current_setting(''app.tenant_id'', true), '''')::uuid)', item || '_tenant_policy', item);
  END LOOP;
END $$;
COMMIT;
