-- EPIC-10: provider-neutral, minimized customer engagement intelligence.
-- Raw conversation bodies and provider credentials are deliberately absent.
BEGIN;

CREATE TABLE IF NOT EXISTS customer_conversation_events (id varchar(255) PRIMARY KEY, tenant_id uuid NOT NULL REFERENCES tenants(id), conversation_id varchar(255) NOT NULL, provider varchar(96) NOT NULL, channel varchar(32) NOT NULL, external_thread_id varchar(255), external_message_id varchar(255), direction varchar(24) NOT NULL, idempotency_key varchar(255) NOT NULL, content_reference varchar(512), content_hash varchar(255), redacted_excerpt varchar(512), consent_status varchar(24) NOT NULL, language_hints jsonb NOT NULL, event jsonb NOT NULL, occurred_at timestamptz NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), CONSTRAINT customer_conversation_event_tenant_idempotency_uidx UNIQUE (tenant_id, idempotency_key), CONSTRAINT customer_conversation_event_tenant_provider_message_uidx UNIQUE (tenant_id, provider, external_message_id));
CREATE INDEX IF NOT EXISTS customer_conversation_events_tenant_conversation_idx ON customer_conversation_events (tenant_id, conversation_id, occurred_at);
CREATE TABLE IF NOT EXISTS customer_conversation_turns (id varchar(255) PRIMARY KEY, tenant_id uuid NOT NULL REFERENCES tenants(id), conversation_id varchar(255) NOT NULL, event_id varchar(255) NOT NULL REFERENCES customer_conversation_events(id) ON DELETE CASCADE, direction varchar(24) NOT NULL, content_reference varchar(512), content_hash varchar(255), redacted_excerpt varchar(512), turn jsonb NOT NULL, occurred_at timestamptz NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), CONSTRAINT customer_conversation_turn_tenant_event_uidx UNIQUE (tenant_id, event_id));
CREATE TABLE IF NOT EXISTS customer_conversation_states (id varchar(255) PRIMARY KEY, tenant_id uuid NOT NULL REFERENCES tenants(id), conversation_id varchar(255) NOT NULL, state varchar(32) NOT NULL, state_record jsonb NOT NULL, updated_at timestamptz NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), CONSTRAINT customer_conversation_state_tenant_conversation_uidx UNIQUE (tenant_id, conversation_id));
CREATE TABLE IF NOT EXISTS customer_conversation_intents (id varchar(255) PRIMARY KEY, tenant_id uuid NOT NULL REFERENCES tenants(id), conversation_id varchar(255) NOT NULL, primary_intent varchar(64) NOT NULL, intent jsonb NOT NULL, detected_at timestamptz NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS customer_conversation_summaries (id varchar(255) PRIMARY KEY, tenant_id uuid NOT NULL REFERENCES tenants(id), conversation_id varchar(255) NOT NULL, summary jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), CONSTRAINT customer_conversation_summary_tenant_conversation_uidx UNIQUE (tenant_id, conversation_id));
CREATE TABLE IF NOT EXISTS conversation_buying_signals (id varchar(255) PRIMARY KEY, tenant_id uuid NOT NULL REFERENCES tenants(id), conversation_id varchar(255) NOT NULL, lead_id varchar(255), signal_type varchar(64) NOT NULL, signal jsonb NOT NULL, occurred_at timestamptz NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS lead_engagement_assessments (id varchar(255) PRIMARY KEY, tenant_id uuid NOT NULL REFERENCES tenants(id), lead_id varchar(255) NOT NULL, state varchar(32) NOT NULL, assessment jsonb NOT NULL, assessed_at timestamptz NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), CONSTRAINT lead_engagement_assessment_tenant_lead_uidx UNIQUE (tenant_id, lead_id));
CREATE TABLE IF NOT EXISTS response_recommendations (id varchar(255) PRIMARY KEY, tenant_id uuid NOT NULL REFERENCES tenants(id), conversation_id varchar(255) NOT NULL, action varchar(64) NOT NULL, expires_at timestamptz NOT NULL, recommendation jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS contactability_assessments (id varchar(255) PRIMARY KEY, tenant_id uuid NOT NULL REFERENCES tenants(id), identity_id varchar(255), lead_id varchar(255), channel varchar(32) NOT NULL, purpose varchar(32) NOT NULL, status varchar(24) NOT NULL, assessment jsonb NOT NULL, assessed_at timestamptz NOT NULL, expires_at timestamptz, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS ai_receptionist_profiles (id varchar(255) PRIMARY KEY, tenant_id uuid NOT NULL REFERENCES tenants(id), enabled boolean NOT NULL DEFAULT false, profile jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS ai_receptionist_sessions (id varchar(255) PRIMARY KEY, tenant_id uuid NOT NULL REFERENCES tenants(id), conversation_id varchar(255) NOT NULL, profile_id varchar(255) NOT NULL, state varchar(32) NOT NULL, idempotency_key varchar(255) NOT NULL, session jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), CONSTRAINT ai_receptionist_session_tenant_idempotency_uidx UNIQUE (tenant_id, idempotency_key));
CREATE TABLE IF NOT EXISTS ai_receptionist_turns (id varchar(255) PRIMARY KEY, tenant_id uuid NOT NULL REFERENCES tenants(id), session_id varchar(255) NOT NULL REFERENCES ai_receptionist_sessions(id) ON DELETE CASCADE, event_id varchar(255), idempotency_key varchar(255) NOT NULL, turn jsonb NOT NULL, occurred_at timestamptz NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), CONSTRAINT ai_receptionist_turn_tenant_idempotency_uidx UNIQUE (tenant_id, idempotency_key));
CREATE TABLE IF NOT EXISTS ai_receptionist_action_recommendations (id varchar(255) PRIMARY KEY, tenant_id uuid NOT NULL REFERENCES tenants(id), session_id varchar(255) NOT NULL REFERENCES ai_receptionist_sessions(id) ON DELETE CASCADE, action varchar(64) NOT NULL, recommendation jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS ai_receptionist_handoffs (id varchar(255) PRIMARY KEY, tenant_id uuid NOT NULL REFERENCES tenants(id), session_id varchar(255) NOT NULL REFERENCES ai_receptionist_sessions(id) ON DELETE CASCADE, target varchar(64) NOT NULL, status varchar(32) NOT NULL, handoff jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS ai_receptionist_outcomes (id varchar(255) PRIMARY KEY, tenant_id uuid NOT NULL REFERENCES tenants(id), session_id varchar(255) NOT NULL REFERENCES ai_receptionist_sessions(id) ON DELETE CASCADE, outcome jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS customer_handoff_recommendations (id varchar(255) PRIMARY KEY, tenant_id uuid NOT NULL REFERENCES tenants(id), conversation_id varchar(255) NOT NULL, target varchar(64) NOT NULL, recommendation jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS customer_handoff_records (id varchar(255) PRIMARY KEY, tenant_id uuid NOT NULL REFERENCES tenants(id), conversation_id varchar(255) NOT NULL, target varchar(64) NOT NULL, status varchar(32) NOT NULL, handoff jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS customer_meeting_intents (id varchar(255) PRIMARY KEY, tenant_id uuid NOT NULL REFERENCES tenants(id), conversation_id varchar(255) NOT NULL, meeting_intent jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS customer_follow_up_recommendations (id varchar(255) PRIMARY KEY, tenant_id uuid NOT NULL REFERENCES tenants(id), conversation_id varchar(255) NOT NULL, expires_at timestamptz NOT NULL, recommendation jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS customer_commitments (id varchar(255) PRIMARY KEY, tenant_id uuid NOT NULL REFERENCES tenants(id), conversation_id varchar(255) NOT NULL, commitment jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS business_commitments (id varchar(255) PRIMARY KEY, tenant_id uuid NOT NULL REFERENCES tenants(id), conversation_id varchar(255) NOT NULL, commitment jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS conversation_diagnostics (id varchar(255) PRIMARY KEY, tenant_id uuid NOT NULL REFERENCES tenants(id), conversation_id varchar(255) NOT NULL, severity varchar(16) NOT NULL, diagnostic jsonb NOT NULL, generated_at timestamptz NOT NULL, created_at timestamptz NOT NULL DEFAULT now());

DO $$ DECLARE item text; BEGIN
  FOREACH item IN ARRAY ARRAY['customer_conversation_events','customer_conversation_turns','customer_conversation_states','customer_conversation_intents','customer_conversation_summaries','conversation_buying_signals','lead_engagement_assessments','response_recommendations','contactability_assessments','ai_receptionist_profiles','ai_receptionist_sessions','ai_receptionist_turns','ai_receptionist_action_recommendations','ai_receptionist_handoffs','ai_receptionist_outcomes','customer_handoff_recommendations','customer_handoff_records','customer_meeting_intents','customer_follow_up_recommendations','customer_commitments','business_commitments','conversation_diagnostics'] LOOP
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', item);
    EXECUTE format('DROP POLICY IF EXISTS %I ON %I', item || '_tenant_policy', item);
    EXECUTE format('CREATE POLICY %I ON %I USING (tenant_id = NULLIF(current_setting(''app.tenant_id'', true), '''')::uuid) WITH CHECK (tenant_id = NULLIF(current_setting(''app.tenant_id'', true), '''')::uuid)', item || '_tenant_policy', item);
  END LOOP;
END $$;
DO $$ DECLARE item text; BEGIN
  FOREACH item IN ARRAY ARRAY['customer_conversation_events','customer_conversation_turns','customer_conversation_states','customer_conversation_intents','customer_conversation_summaries','conversation_buying_signals','lead_engagement_assessments','response_recommendations','contactability_assessments','ai_receptionist_profiles','ai_receptionist_sessions','ai_receptionist_turns','ai_receptionist_action_recommendations','ai_receptionist_handoffs','ai_receptionist_outcomes','customer_handoff_recommendations','customer_handoff_records','customer_meeting_intents','customer_follow_up_recommendations','customer_commitments','business_commitments','conversation_diagnostics'] LOOP
    EXECUTE format('ALTER TABLE %I ADD COLUMN IF NOT EXISTS updated_at timestamptz NOT NULL DEFAULT now()', item);
  END LOOP;
END $$;
COMMIT;
