-- EPIC-12: provider-neutral lifecycle activation. These records never authorize provider transport.
BEGIN;
CREATE TABLE IF NOT EXISTS lifecycle_activation_plans (id varchar(255) PRIMARY KEY, tenant_id uuid NOT NULL REFERENCES tenants(id), identity_id varchar(255) NOT NULL, next_best_action_id varchar(255) NOT NULL, status varchar(32) NOT NULL, idempotency_key varchar(255) NOT NULL, plan jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), CONSTRAINT lifecycle_activation_plan_tenant_key_uidx UNIQUE (tenant_id, idempotency_key));
CREATE TABLE IF NOT EXISTS lifecycle_activation_steps (id varchar(255) PRIMARY KEY, tenant_id uuid NOT NULL REFERENCES tenants(id), plan_id varchar(255) NOT NULL REFERENCES lifecycle_activation_plans(id) ON DELETE CASCADE, sequence integer NOT NULL, status varchar(32) NOT NULL, step jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), CONSTRAINT lifecycle_activation_step_tenant_plan_sequence_uidx UNIQUE (tenant_id, plan_id, sequence));
CREATE TABLE IF NOT EXISTS lifecycle_activation_candidates (id varchar(255) PRIMARY KEY, tenant_id uuid NOT NULL REFERENCES tenants(id), plan_id varchar(255) NOT NULL REFERENCES lifecycle_activation_plans(id) ON DELETE CASCADE, identity_id varchar(255) NOT NULL, channel varchar(64) NOT NULL, status varchar(32) NOT NULL, idempotency_key varchar(255) NOT NULL, candidate jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), CONSTRAINT lifecycle_activation_candidate_tenant_key_uidx UNIQUE (tenant_id, idempotency_key));
CREATE TABLE IF NOT EXISTS lifecycle_activation_assessments (id varchar(255) PRIMARY KEY, tenant_id uuid NOT NULL REFERENCES tenants(id), candidate_id varchar(255) NOT NULL REFERENCES lifecycle_activation_candidates(id) ON DELETE CASCADE, assessment_type varchar(32) NOT NULL, assessment jsonb NOT NULL, assessed_at timestamptz NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS lifecycle_activation_executions (id varchar(255) PRIMARY KEY, tenant_id uuid NOT NULL REFERENCES tenants(id), candidate_id varchar(255) NOT NULL REFERENCES lifecycle_activation_candidates(id) ON DELETE CASCADE, status varchar(32) NOT NULL, idempotency_key varchar(255) NOT NULL, execution jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), CONSTRAINT lifecycle_activation_execution_tenant_key_uidx UNIQUE (tenant_id, idempotency_key));
CREATE TABLE IF NOT EXISTS lifecycle_activation_verifications (id varchar(255) PRIMARY KEY, tenant_id uuid NOT NULL REFERENCES tenants(id), execution_id varchar(255) NOT NULL REFERENCES lifecycle_activation_executions(id) ON DELETE CASCADE, status varchar(32) NOT NULL, verification jsonb NOT NULL, verified_at timestamptz NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS lifecycle_activation_outcomes (id varchar(255) PRIMARY KEY, tenant_id uuid NOT NULL REFERENCES tenants(id), identity_id varchar(255) NOT NULL, execution_id varchar(255) REFERENCES lifecycle_activation_executions(id) ON DELETE SET NULL, outcome varchar(16) NOT NULL, idempotency_key varchar(255) NOT NULL, outcome_record jsonb NOT NULL, observed_at timestamptz NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), CONSTRAINT lifecycle_activation_outcome_tenant_key_uidx UNIQUE (tenant_id, idempotency_key));
CREATE TABLE IF NOT EXISTS lifecycle_activation_learning_links (id varchar(255) PRIMARY KEY, tenant_id uuid NOT NULL REFERENCES tenants(id), activation_outcome_id varchar(255) NOT NULL REFERENCES lifecycle_activation_outcomes(id) ON DELETE CASCADE, journey_outcome_id varchar(255), journey_learning_id varchar(255), link jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), CONSTRAINT lifecycle_activation_learning_link_tenant_outcome_uidx UNIQUE (tenant_id, activation_outcome_id));
DO $$ DECLARE item text; BEGIN FOREACH item IN ARRAY ARRAY['lifecycle_activation_plans','lifecycle_activation_steps','lifecycle_activation_candidates','lifecycle_activation_assessments','lifecycle_activation_executions','lifecycle_activation_verifications','lifecycle_activation_outcomes','lifecycle_activation_learning_links'] LOOP EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', item); EXECUTE format('DROP POLICY IF EXISTS %I ON %I', item || '_tenant_policy', item); EXECUTE format('CREATE POLICY %I ON %I USING (tenant_id = NULLIF(current_setting(''app.tenant_id'', true), '''')::uuid) WITH CHECK (tenant_id = NULLIF(current_setting(''app.tenant_id'', true), '''')::uuid)', item || '_tenant_policy', item); END LOOP; END $$;
COMMIT;
