-- EPIC-13: deterministic, provider-neutral growth decisioning; recommendations never authorize execution.
BEGIN;
CREATE TABLE IF NOT EXISTS growth_decision_contexts (id varchar(255) PRIMARY KEY, tenant_id uuid NOT NULL REFERENCES tenants(id), identity_id varchar(255) NOT NULL, idempotency_key varchar(255) NOT NULL, context jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), CONSTRAINT growth_decision_context_tenant_key_uidx UNIQUE (tenant_id, idempotency_key));
CREATE TABLE IF NOT EXISTS growth_action_candidates (id varchar(255) PRIMARY KEY, tenant_id uuid NOT NULL REFERENCES tenants(id), context_id varchar(255) NOT NULL REFERENCES growth_decision_contexts(id) ON DELETE CASCADE, objective varchar(32) NOT NULL, action_type varchar(64) NOT NULL, state varchar(32) NOT NULL, idempotency_key varchar(255) NOT NULL, candidate jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), CONSTRAINT growth_action_candidate_tenant_key_uidx UNIQUE (tenant_id, idempotency_key));
CREATE TABLE IF NOT EXISTS growth_candidate_eligibility_assessments (id varchar(255) PRIMARY KEY, tenant_id uuid NOT NULL REFERENCES tenants(id), candidate_id varchar(255) NOT NULL REFERENCES growth_action_candidates(id) ON DELETE CASCADE, eligible boolean NOT NULL, assessment jsonb NOT NULL, assessed_at timestamptz NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS growth_decision_conflict_assessments (id varchar(255) PRIMARY KEY, tenant_id uuid NOT NULL REFERENCES tenants(id), candidate_id varchar(255) NOT NULL REFERENCES growth_action_candidates(id) ON DELETE CASCADE, conflict boolean NOT NULL, assessment jsonb NOT NULL, assessed_at timestamptz NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS growth_decision_scores (id varchar(255) PRIMARY KEY, tenant_id uuid NOT NULL REFERENCES tenants(id), candidate_id varchar(255) NOT NULL REFERENCES growth_action_candidates(id) ON DELETE CASCADE, score integer NOT NULL, components jsonb NOT NULL, scored_at timestamptz NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS growth_decision_recommendations (id varchar(255) PRIMARY KEY, tenant_id uuid NOT NULL REFERENCES tenants(id), context_id varchar(255) NOT NULL REFERENCES growth_decision_contexts(id) ON DELETE CASCADE, candidate_id varchar(255) NOT NULL REFERENCES growth_action_candidates(id) ON DELETE CASCADE, state varchar(32) NOT NULL, idempotency_key varchar(255) NOT NULL, recommendation jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), CONSTRAINT growth_decision_recommendation_tenant_key_uidx UNIQUE (tenant_id, idempotency_key));
CREATE TABLE IF NOT EXISTS growth_decision_outcomes (id varchar(255) PRIMARY KEY, tenant_id uuid NOT NULL REFERENCES tenants(id), recommendation_id varchar(255) NOT NULL REFERENCES growth_decision_recommendations(id) ON DELETE CASCADE, outcome varchar(16) NOT NULL, idempotency_key varchar(255) NOT NULL, outcome_record jsonb NOT NULL, observed_at timestamptz NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), CONSTRAINT growth_decision_outcome_tenant_key_uidx UNIQUE (tenant_id, idempotency_key));
CREATE TABLE IF NOT EXISTS growth_decision_learning_records (id varchar(255) PRIMARY KEY, tenant_id uuid NOT NULL REFERENCES tenants(id), outcome_id varchar(255) NOT NULL REFERENCES growth_decision_outcomes(id) ON DELETE CASCADE, learning jsonb NOT NULL, recorded_at timestamptz NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), CONSTRAINT growth_decision_learning_tenant_outcome_uidx UNIQUE (tenant_id, outcome_id));
CREATE INDEX IF NOT EXISTS growth_action_candidates_tenant_context_idx ON growth_action_candidates (tenant_id, context_id);
CREATE INDEX IF NOT EXISTS growth_candidate_eligibility_tenant_candidate_idx ON growth_candidate_eligibility_assessments (tenant_id, candidate_id);
CREATE INDEX IF NOT EXISTS growth_decision_conflicts_tenant_candidate_idx ON growth_decision_conflict_assessments (tenant_id, candidate_id);
CREATE INDEX IF NOT EXISTS growth_decision_scores_tenant_candidate_idx ON growth_decision_scores (tenant_id, candidate_id);
CREATE INDEX IF NOT EXISTS growth_decision_recommendations_tenant_context_idx ON growth_decision_recommendations (tenant_id, context_id);
CREATE INDEX IF NOT EXISTS growth_decision_outcomes_tenant_recommendation_idx ON growth_decision_outcomes (tenant_id, recommendation_id);
DO $$ DECLARE item text; BEGIN FOREACH item IN ARRAY ARRAY['growth_decision_contexts','growth_action_candidates','growth_candidate_eligibility_assessments','growth_decision_conflict_assessments','growth_decision_scores','growth_decision_recommendations','growth_decision_outcomes','growth_decision_learning_records'] LOOP EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', item); EXECUTE format('DROP POLICY IF EXISTS %I ON %I', item || '_tenant_policy', item); EXECUTE format('CREATE POLICY %I ON %I USING (tenant_id = NULLIF(current_setting(''app.tenant_id'', true), '''')::uuid) WITH CHECK (tenant_id = NULLIF(current_setting(''app.tenant_id'', true), '''')::uuid)', item || '_tenant_policy', item); END LOOP; END $$;
COMMIT;
